### ISSUE TITLE
Click graph visualization

### ISSUE THREAD

**Issue by tbarbette** [tbarbette/fastclick#104]
Aside Clicky that can export the graph visualization in PDF, what other tools do you guys now about ?

I'll try to make a wiki page out of this question.

**Comment by bcronje** [comment]
I've used [click-viz](https://github.com/kohler/click/blob/master/tools/click-viz) that uses click-pretty before:


```
# click-viz : a program to graphically visualize click scripts.
#
# The output of this program is meant to be piped to dot to
# generate a graph. Examples:
#	click-viz demo.click | dot -Tpng >demo.png
#       click-flatten demo.click | click-viz | dot -Tpng >demo.png

```

**Comment by bcronje** [comment]
I believe click-pretty can also export to html as well.

**Comment by piotrjurkiewicz** [comment]
Graphs in the Click paper were generated using [MetaPost](https://github.com/tbarbette/fastclick/tree/master/etc/diagrams). It works out of the box with modern LaTeX distributions (Miktex for example, command `mptopdf xxx.mp`), but diagrams cannot be generated automatically from Click configuration files. They must be written manually.

**Comment by cffs** [comment]
Generating the graphs automatically for MetaPost (or TikZ, or ...) might be feasible, but we would need to come up with our own node placement algorithm, as MetaPost requires *some* positioning information.

Improving the dot output would be an easier short-term target. It can be done by tweaking a bit the dot code itself, but would likely require post-processing of the output (should not be too hard using the SVG backend).

Finally, we could generate code for a modern alternative to dot, which handles node placement but also allows more customization of the look. Any suggestions?

**Comment by bcronje** [comment]
Personally I would rather look into something that generates graphs that look something like Meraki's [topology map](https://meraki.cisco.com/blog/2014/10/topology-the-map-youve-been-missing/). I'm just guessing here but they probably uses D3 or similar javascript library to generate the map. Any Meraki guys want to comment on what library is used for that map?

**Comment by tbarbette** [comment]
I guess JS would be something different, for live view ?

I'm dreaming for a web interface allowing to drag and drop elements. The HTTPServer element is already very useful to use a REST (or web) interface to play with elements parameters.

But the original question is about "paper" visualization. Are there template for MetaPost Click-like elements ? I mean with the little square or triangles for push/pull, etc

**Comment by tbarbette** [comment]
Maybe @pallas can help here?

**Comment by cffs** [comment]
Some .js frameworks work on SVG which can then be exported for use in papers. It also has the advantage of limiting the dependencies as we can likely ship the .js library directly with the tool (depending on its license). But which one would be more appropriate?

If we choose to go the MetaPost route instead, I should be able to re-write element template macros if needed. However, we still need to find a way to position the elements. Maybe we could reuse dot output as illustrated in [Supporting layout routines in MetaPost](https://www.tug.org/TUGboat/tb30-1/tb94zheng.pdf).

**Comment by bcronje** [comment]
Never mind, found HTTPServer description in the [commit message](https://github.com/tbarbette/fastclick/commit/7dc203167c7bf84ea95dc6b7469d837fe831661c#diff-ecb766a394ef3ac375836b5d2073a1bc).

On that note we should probably start enforcing that new/updated elements use the Click style element documentation inside the header files?

**Comment by tbarbette** [comment]
Yes we should. I'm trying to go through pull requests for most changes now. Don't hesitate to beat me if that happens again :p

**Comment by tbarbette** [comment]
For further reference, the metapost examples are actually available in etc/diagrams
