### ISSUE TITLE
Packets are not being sent out with VF

### ISSUE THREAD

**Issue by lapd-viosoft** [tbarbette/fastclick#11]
Hi all,
I try to run fast click with SRIOV-VF (virtual function) as follow

;================            ;==================
|                         NIC1-----------NIC1-VF1                     |
| Traffic generator |                 |         SUT   l2fwd-click |
|                         NIC2----------NIC2-VF1                      |
;================;            ; =================

l2fwd.click
thread1:: FromDPDKDevice(0,MAXTHREADS 1, PROMISC true,BURST 32) -> ToDPDKDevice(1, BLOCKING true);
thread2:: FromDPDKDevice(1,MAXTHREADS 1, PROMISC true,BURST 32) ->  ToDPDKDevice(0, BLOCKING true);
StaticThreadSched(thread1 0, thread2 1);

L2FWD-Click can received packets (I checked by insert Print(ok) element in the .click file above)
However, the packets never comeback to the Traffic generator, it seems at SUT, that packets never send out.
According to this link http://dpdk.org/doc/guides/rel_notes/known_issues.html#packets-are-not-sent-by-the-1-gbe-10-gbe-sr-iov-driver-when-the-source-mac-is-not-the-mac-assigned-to-the-vf-nic
I already update click ToDPDKDevice element to configure the Ethernet source address in each packet to match that of the VF NIC but no luck
Can you suggest me some direction?
P/S: The connection between two servers are back-back (no switch)
Thank and Best Regards
Lapd

**Comment by tbarbette** [comment]
Hi,
I suggest not relying on promisc to start, using the EtherRewrite element before ToDPDKDevice (editing the element is not very click-like). EtherRewrite will allow to set the correct source and destination address. Source is needed for the spoofing protection you cite, but destination is needed to reach the good PF/VF. I'm not sure how promisc behave in VFs. Having VF in promisc mode may not be allowed as you could steal traffic from other VFs, defeating the isolation?

Tom

**Comment by lapd-viosoft** [comment]
Hi Tbarbette,
Thank for your suggestion. 
Setting up promisc to false doesn't help resolve issue.
Use EtherRewrite element raise Segmentation fault issue. I guest it's from small buffer size.
However,EtherEncap element helps resolve issue. Packets are coming back to traffic generator machine.
Lapd

**Comment by tbarbette** [comment]
Great! For posterity, the EtherRewrite element needs the mac header annotation, which have to be set using the MarkMACHeader as FromDPDKDevice does not set it.
