### ISSUE TITLE
How to let an element self-increment a passed config parameter per time unit?

### ISSUE THREAD

**Issue by kthkaya** [tbarbette/fastclick#126]
Hello,

I am using UDPIP6ENCAP element in my packet generator code and I need to introduce a "unique flows per second" feature. I am thinking of a configuration parameter "fps" accepting an integer n, and implement a function that polls systime and increments the [_saddr](https://github.com/tbarbette/fastclick/blob/master/elements/tcpudp/udpip6encap.cc#L69) every 1/n seconds increase in systime.

If you think this is an acceptable approach, what would be the best way to call this increment function on its own thread so that it doesnt lie on the fastpath? And do you think `UDPIP6Encap::configure(Vector<String> &conf, ErrorHandler *errh)
` is the appropriate place to call it?

Thanks!

**Comment by tbarbette** [comment]
Don't spawn thread in Click. Use a Click thread by assigning some element with StaticThreadSched.

It seems what you want to do is to change the configuration of UDPIP6ENCAP every second. I would suggest making a script element like that : 

s :: Script( TYPE ACTIVE,
           label loop,
           wait 1s,
           set ip udpencap.saddr,
           write udpencap.saddr $(add $ip 1),
           goto loop);
StaticThreadSched(s 2);
Assuming the element has an saddr read/write handler. Maybe easier, just create a handler named "inc_saddr" that will add 1 to the IP address. I'm not sure of the behavior of the code above because of endianess. Then you can call "write udpencap.inc_saddr" to simply call the handler.

Tom


>

**Comment by kthkaya** [comment]
Thanks for the response Tom.

> It seems what you want to do is to change the configuration of UDPIP6ENCAP every second

It will be less than a second. If 1000 unique flows per second is requested, the config needs to change every milisecond. The change has to happen at microseconds if more than 1000 unique flows are requested.

The Script element wiki states that the wait argument has microseconds precision, but can it  accept 0.001s or less?

> Maybe easier, just create a handler named "inc_saddr" that will add 1 to the IP address

Yep, I will follow this approach if the Script element can wait for mili or microseconds.

**Comment by tbarbette** [comment]
Milli yes, micro no. But you may create a "cron" element that is more efficient at poking some handler

**Comment by bcronje** [comment]
It might just be quicker/easier to extend UDPIP6Encap. Just use a Click timer to increment the address. Or if very high fps rate is required, use a tokenbucket with Click Task, see RatedSource or similar element on how to implement this.

**Comment by tbarbette** [comment]
True, but I don't like elements being extended/duplicated for every feature. I think if "it" can be done with a combination of element, it's the best path.

**Comment by kthkaya** [comment]
Thanks for the input guys!

**Comment by kthkaya** [comment]
So here is how the code looks like

```
/------------Declarations-----------

//+++++DPDK0 Interface(Inside)+++++
DPDK0_OUT ::  ToDPDKDevice(0);

//+++++DPDK1 Interface(Outside)+++++
DPDK1_IN :: FromDPDKDevice(1, PROMISC true);

udpEncap :: UDPIP6Encap(2001:2001:2001:2001::1, 1234, 64:ff9b::192.168.2.5, 1234)

//--------Program Start----------
InfiniteSource(LENGTH 64, LIMIT 1500000, STOP true)
        -> NumberPacket(OFFSET 0)
	-> udpEncap
        -> EtherEncap(0x86DD, 00:04:23:D0:93:63, 00:17:cb:0d:f8:db)
        -> record :: RecordTimestamp()
        -> DPDK0_OUT;

s :: Script( TYPE ACTIVE,
	label loop,
	wait 1s,
	set ip udpEncap.src,
	write udpEncap.src $(add $ip 1),
	goto loop );

StaticThreadSched(s 2);

DPDK1_IN
        -> CheckNumberPacket(OFFSET 62, COUNT 1500000)
        -> diff :: TimestampDiff(OFFSET 62, RECORDER record)
        -> counter :: AverageCounter()
        -> Discard;
//--------Program End----------

DriverManager(wait,read diff.average, read counter.count, read counter.rate)
```
I get the following warning

> While executing 's :: Script':
  expected list of numbers

I guess _add_ is not liking an IPv6 address as an int as it is 16 bytes?

**Comment by kthkaya** [comment]
> Maybe easier, just create a handler named "inc_saddr" that will add 1 to the IP address.

Ended up following this advice and it works. Thanks!
