### ISSUE TITLE
expensive Packet::push; have 12 wanted 14

### ISSUE THREAD

**Issue by kthkaya** [tbarbette/fastclick#132]
I have the following packet generator/sink

```
//------------Declarations-----------
DPDK0_OUT ::  ToDPDKDevice(0);

//+++++DPDK1 Interface(Outside)+++++
DPDK1_IN :: FromDPDKDevice(1, PROMISC true);

//--------Program Start----------
//InfiniteSource(LENGTH 64, LIMIT 150000, STOP true)
RatedSource(LENGTH 64, RATE 7000, LIMIT 150000, STOP true)
        -> NumberPacket(OFFSET 0)
        -> UDPIP6Encap(2001:2001:2001:2001::1, 1234, 64:ff9b::192.168.2.5, 1234)
        -> EtherEncap(0x86DD, 00:04:23:D0:93:63, 00:17:cb:0d:f8:db)
        -> record :: RecordTimestamp()
        -> DPDK0_OUT;

DPDK1_IN
        -> CheckNumberPacket(OFFSET 62, COUNT 150000)
        -> diff :: TimestampDiff(OFFSET 62, RECORDER record)
        -> counter :: AverageCounter()
        -> Discard;
//--------Program End----------

DriverManager(wait,read diff.average, read counter.count, read counter.rate)
```

When I run it, I get the following warning,

> expensive Packet::push; have 12 wanted 14

Everything works just fine if I use InfiniteSource instead of RatedSource (comment out the RatedSource line and uncomment the InfiniteSource line). 

Any ideas?

**Comment by bcronje** [comment]
InfiniteSource uses a larger default packet headroom when it creates the packet. It is also configurable. Where RatedSource uses a smaller header size which ends up as less than the space needed by your two encap elements. The end result is Click will then have to reallocate the packet memory to cater for the packet size, hence the "expensive push" warning.

Everything should work, it just warns about the additional memory allocation and copy. 

RatedSource could be updated to also accept a header argument maybe?

**Comment by tbarbette** [comment]
You have to ensure there is enough headroom for the packet. It means when you encap the packet data has to be moved. If RatedSource has no option to add some more headroom, you'll have to add one.

**Comment by kthkaya** [comment]
Thanks Beyers, 

I could work on a handler for that, however there is a note about click-align. I don't know what click-align is used for.
https://github.com/tbarbette/fastclick/blob/8c9352e5c702c91fc001f626ab813477f0e477b0/elements/standard/ratedsource.cc#L255-L256

Perhaps L255-L256 can be substituted with the following
https://github.com/tbarbette/fastclick/blob/e30dab82652491dd93be7861131a235bac9017e7/elements/standard/infinitesource.cc#L60

**Comment by tbarbette** [comment]
Click-align ensures that access to bytes of the packet are always on the architecture word size boundary by introducing "Align" elements here and there.  I doubt anyone is still using an arch where accessing un-aligned bytes is more costly than moving the whole packets multiple times in memory, though...  @pallas ?

I think you can safely also use default_headroom here. And making it a configuration option still allows people to revert to the normal behavior.

**Comment by kthkaya** [comment]
Thanks guys, the warning now disappeared.
https://github.com/tbarbette/fastclick/pull/133
