### ISSUE TITLE
Strange assertion error on some IPFilter configurations

### ISSUE THREAD

**Issue by cffs** [tbarbette/fastclick#159]
Some (admittedly dubious) IPFilter configurations result in an assertion error when the router is built.

I built FastClick with

    ./configure --prefix=/home/soldani/devel/fastclick/prefix RTE_SDK=$RTE_SDK \
        RTE_TARGET=$RTE_TARGET --enable-dpdk --enable-user-multithread --disable-linuxmodule

I try to run the following minimal testcase configuration:

```
fd :: InfiniteSource();
ipf :: IPFilter(
    drop tcp opt psh and ip proto 168,
    drop ip[2:2] 40,
    allow all
);
td :: Discard();

fd -> ipf -> td;
```

Loading this router with `./userlevel/click conf/testcase.click` fails with

    click: ../include/click/vector.hh:291: T& Vector<T>::operator[](Vector<T>::size_type)
    [with T = int; Vector<T>::size_type = int]: Assertion `(unsigned) i < (unsigned) vm_.n_'
    failed.

Here is a relevant extract of the GDB backtrace:

```
#3  0x00007ffff789e0a2 in __GI___assert_fail (assertion=assertion@entry=0x555555c27190 "(unsigned) i < (unsigned) vm_.n_", file=file@entry=0x555555c27140 "../include/click/vector.hh", 
    line=line@entry=291, 
    function=function@entry=0x555555c3a4a0 <_ZZN6VectorIiEixEiE19__PRETTY_FUNCTION__> "T& Vector<T>::operator[](Vector<T>::size_type) [with T = int; Vector<T>::size_type = int]")
    at assert.c:101
#4  0x0000555555845a73 in Vector<int>::operator[] (this=<optimized out>, this=<optimized out>, i=5) at ../include/click/vector.hh:290
#5  0x000055555584a7b7 in Vector<int>::operator[] (this=<optimized out>, this=<optimized out>, i=<optimized out>) at ../include/click/vector.hh:290
#6  Vector<int>::back (this=<optimized out>) at ../include/click/vector.hh:333
#7  Classification::Wordwise::DominatorOptimizer::calculate_dom (this=0x7fffffffdb20, state=5) at ../elements/standard/classification.cc:459
#8  0x000055555584aad8 in Classification::Wordwise::DominatorOptimizer::run (this=0x7fffffffdb20, state=5) at ../elements/standard/classification.cc:694
#9  0x000055555584ab5a in Classification::Wordwise::Program::optimize (this=0x5555563b2b00, 
    offset_map_begin=offset_map_begin@entry=0x555555c33a70 <IPFilter::parse_program(Classification::Wordwise::CompressedProgram&, Vector<String> const&, int, Element const*, ErrorHandler*)::offset_map>, offset_map_end=offset_map_end@entry=0x555555c33a78, last_offset=last_offset@entry=2147483647) at ../elements/standard/classification.cc:892
#10 0x0000555555828c7a in IPFilter::parse_program (zprog=..., conf=..., noutputs=1, context=0x5555563c06c0, errh=0x7fffffffde90) at ../include/click/vector.hh:290
```

It looks like the failing function is `Vector<int>::back` in

    assert(_dom_start.size() - 1 == _domlist_start.back());

at `elements/standard/classification.cc:459`. In GDB, it appears OK relatively to indexing, with `_domlist_start.vm_.n_` equal to 6, which corresponds to the index 5 that we see in backtrace `#4`. But if I add a `printf` in `Vector::operator[]`, the argument seems to actually be -1 (4294967295 once cast to unsigned). I guess there is either an optimization problem, or some memory corruption going on.

If the `ip proto` is changed to 6 (for TCP, in line with inspecting the `PSH` flag), the error goes away. It also disappear if I remove either of the `drop` lines. On the other hand, this is just one example of strange interaction between rules that trigger this assertion. We use a randomly-generated rule set and this assertion error fires as soon as we used more than a few hundreds random rules.

Any idea what is causing this? While obviously not critical (we had no problem with simple 5tuple matching, and when using the right IP proto), this is still quite puzzling.

**Comment by tbarbette** [comment]
This seems to be happening because of the ip[2:2] as changing that by any other matching syntax works. Like "ip dst port 20".
Also this happens at initialization time, so it's a pure rule parsing problem. Probably there in vanilla Click. But I'll try to advance on this anyway.

**Comment by tbarbette** [comment]
I don't know much about this. Maybe it's best if you post this to mainline Click ?

**Comment by cffs** [comment]
Yes, I'll do that. Thanks for having a look. Closing here.
