### ISSUE TITLE
KNI

### ISSUE THREAD

**Issue by johnpearson555** [tbarbette/fastclick#18]
DPDK KNI

After classifying packets in Click, I would like to send packets to a linux app. Is there a way to do this without a Tun/Tap interface so that there aren't system calls?

Is there a way to send and receive packets on a KNI interface within a fastclick configuration?

**Comment by tbarbette** [comment]
Hi,

I looked a little more at rte_kni.h (http://dpdk.org/doc/api/rte__kni_8h.html,) after our discussion in private, it seems that nearly everything has to be initiated by the application, meaning that FromKNIDevice/ToKNIDevice elements should be built from scratch (or I would suggest inheriting FromDPDKDevice or a common base as some things can be re-used).

I do not have time for that now. I will probably have a Master student doing it but not in a very near future.

Tom
