### ISSUE TITLE
Need help on Click + DPDK + TAP Software NIC

### ISSUE THREAD

**Issue by maulikpatel1990** [tbarbette/fastclick#183]
Hi All,

I am new to Click and DPDK and I want to explore it somewhat with Software NIC. As of now I am planning to start with TAP software NIC but I am not able to get everything setup successfully. It would be greate if someone can point me to any documentation/guide/links available on how to do so.

Thanks in advance for your help.

Regards,
Maulik Patel

**Comment by tbarbette** [comment]
Can you precise a little your problem? Did you follow the tutorial in the wiki which uses KernelTAP actually? Would probably a good starting point.

Good luck !

Tom

**Comment by maulikpatel1990** [comment]
Hi Tom,

Sorry for coming back somewhat late on this. Actually I was thinking to do some experiments with Fastclick + DPDK and at my end I do not have any hardware supported NIC. so I was thinking to do some experiments with Software NICs.

After some exploration I came to know that by passing "_--vdev 'net_tap,iface=tap0'_" argument to dpdk it automatically creates and initialize new tap interface. So no need to do that manually.

For other people like me who are new to this, below is the full click command to run click and dpdk on tap interface:
_click --dpdk -c '0x1' -n 4  --vdev 'net_tap,iface=tap0' -- conf/dpdk/dpdk-bounce.click_

Regards,
Maulik Patel

**Comment by tbarbette** [comment]
Updated https://github.com/tbarbette/fastclick/wiki/High-speed-I-O with it. Thanks
