### ISSUE TITLE
recipe for target 'click' failed

### ISSUE THREAD

**Issue by ligang626** [tbarbette/fastclick#188]
/stdio/dpdk//build/lib/librte_mempool_octeontx.a(octeontx_fpavf.o):octeontx_fpavf.c:(.text+0x52c): more undefined references to `octeontx_mbox_send' follow
collect2: error: ld returned 1 exit status
Makefile:152: recipe for target 'click' failed
make[1]: *** [click] Error 1
make[1]: Leaving directory '/opt/raymax/git/fastclick-metron/userlevel'
Makefile:57: recipe for target 'userlevel' failed
make: *** [userlevel] Error 2

**Comment by tbarbette** [comment]
This is related to DPDK. Which version are you using ?

**Comment by ligang626** [comment]
The current version of dpdk18.05
Dpdk17.05 and 19.05 have tried

> 这与DPDK有关。你使用的是哪个版本？

**Comment by tbarbette** [comment]
Did you enable something special when building DPDK? What is your Linux distribution and version?

If you're looking for a quick fix, you can probably remove any line containing "octeon" in userlevel/dpdk.mk

**Comment by ligang626** [comment]
I am using ubuntu16.04

About dpdk
I executed the following command:
make config T=x86_64-native-linuxapp-gcc
sed -ri 's,(PMD_PCAP=).*,\1y,' build/.config
make




gang.li@raymax.net
 
From: Tom Barbette
Date: 2019-08-02 16:16
To: tbarbette/fastclick
CC: ligang626; Author
Subject: Re: [tbarbette/fastclick] recipe for target 'click' failed (#188)
Did you enable something special when building DPDK? What is your Linux distribution and version?
If you're looking for a quick fix, you can probably remove any line containing "octeon" in userlevel/dpdk.mk

**Comment by tbarbette** [comment]
You're on the metron branch then? Given your other issue, I guess you fixed this? As it finally built?

**Comment by ligang626** [comment]
I use dpdk17.05, the metron branch of fastclick.
At present, such an environment has been completed.
But I don't know how it is done.
Then when I try again on other servers,
After the fastclick configure command, the display does not support metron
And make an error

**Comment by gkatsikas** [comment]
Could you please post the error message here?

**Comment by ligang626** [comment]
CXX ../elements/wifi/station/beaconscanner.cc
  CXX ../elements/wifi/station/beacontracker.cc
  CXX ../elements/wifi/station/openauthrequester.cc
  CXX ../elements/wifi/station/proberequester.cc
  CREATE elements.cc
  CXX elements.cc
  CXX click.cc
  LINK click
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(ssovf_evdev.o): In function `octeontx_pki_port_modify_qos':
ssovf_evdev.c:(.text+0x24a): undefined reference to `octeontx_mbox_send'
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(ssovf_evdev.o): In function `octeontx_pki_port_delete_qos':
ssovf_evdev.c:(.text+0x2d1): undefined reference to `octeontx_mbox_send'
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(ssovf_evdev.o): In function `ssovf_mbox_dev_info':
ssovf_evdev.c:(.text+0x3b8): undefined reference to `octeontx_mbox_send'
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(ssovf_evdev.o): In function `ssovf_mbox_getwork_tmo_set':
ssovf_evdev.c:(.text+0x42f): undefined reference to `octeontx_mbox_send'
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(ssovf_evdev.o): In function `ssovf_mbox_priority_set':
ssovf_evdev.c:(.text+0x4f3): undefined reference to `octeontx_mbox_send'
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(ssovf_evdev.o):ssovf_evdev.c:(.text+0x5cc): more undefined references to `octeontx_mbox_send' follow
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(ssovf_probe.o): In function `ssovf_info':
(.text+0x131): undefined reference to `octeontx_logtype_mbox'
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(ssovf_probe.o): In function `ssovf_info':
(.text+0x245): undefined reference to `octeontx_logtype_mbox'
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(ssovf_probe.o): In function `ssowvf_probe':
ssovf_probe.c:(.text+0x459): undefined reference to `octeontx_logtype_mbox'
ssovf_probe.c:(.text+0x4b1): undefined reference to `octeontx_logtype_mbox'
ssovf_probe.c:(.text+0x517): undefined reference to `octeontx_logtype_mbox'
ssovf_probe.c:(.text+0x5f6): undefined reference to `octeontx_mbox_set_ram_mbox_base'
ssovf_probe.c:(.text+0x600): undefined reference to `octeontx_logtype_mbox'
ssovf_probe.c:(.text+0x650): undefined reference to `octeontx_logtype_mbox'
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(ssovf_probe.o): In function `ssovf_probe':
ssovf_probe.c:(.text+0x6f4): undefined reference to `octeontx_logtype_mbox'
ssovf_probe.c:(.text+0x7b0): undefined reference to `octeontx_logtype_mbox'
ssovf_probe.c:(.text+0x889): undefined reference to `octeontx_mbox_set_reg'
ssovf_probe.c:(.text+0x893): undefined reference to `octeontx_logtype_mbox'
ssovf_probe.c:(.text+0x8e3): undefined reference to `octeontx_logtype_mbox'
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(timvf_evdev.o): In function `timvf_mbox_dev_info_get':
timvf_evdev.c:(.text+0x1407): undefined reference to `octeontx_mbox_send'
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(timvf_evdev.o): In function `timvf_ring_conf_set':
timvf_evdev.c:(.text+0x1528): undefined reference to `octeontx_mbox_send'
/stdio/dpdk//build/lib/librte_pmd_octeontx_ssovf.a(timvf_evdev.o): In function `timvf_get_start_cyc':
timvf_evdev.c:(.text+0x15c6): undefined reference to `octeontx_mbox_send'
/stdio/dpdk//build/lib/librte_mempool_octeontx.a(octeontx_fpavf.o): In function `octeontx_fpapf_pool_setup':
octeontx_fpavf.c:(.text+0x31c): undefined reference to `octeontx_mbox_send'
/stdio/dpdk//build/lib/librte_mempool_octeontx.a(octeontx_fpavf.o): In function `octeontx_fpapf_pool_destroy':
octeontx_fpavf.c:(.text+0x461): undefined reference to `octeontx_mbox_send'
/stdio/dpdk//build/lib/librte_mempool_octeontx.a(octeontx_fpavf.o):octeontx_fpavf.c:(.text+0x534): more undefined references to `octeontx_mbox_send' follow
collect2: error: ld returned 1 exit status
Makefile:152: recipe for target 'click' failed
make[1]: *** [click] Error 1
make[1]: Leaving directory '/opt/raymax/git/fastclick/userlevel'
Makefile:57: recipe for target 'userlevel' failed
make: *** [userlevel] Error 2

**Comment by gkatsikas** [comment]
As Tom suggested above, try to comment lines containing the word 'octeon' in userlevel/dpdk.mk.
For example, comment line 309 in this file:

#_LDLIBS-$(CONFIG_RTE_LIBRTE_PMD_OCTEONTX_SSOVF) += -lrte_pmd_octeontx_ssovf

**Comment by ligang626** [comment]
Thank you. This problem is solved
