### ISSUE TITLE
【Bug】fastclick bug when it hava run ~

### ISSUE THREAD

**Issue by cooper-mc** [tbarbette/fastclick#19]
When we run successfully after fastclick, radio buttons or check boxes will appear in the label content area can't normal triggers the click event
But the padding area can trigger the click event
pray someone to explain
thanks~

**Comment by cooper-mc** [comment]
![brt_e7m0i63m _m5wpszp](https://cloud.githubusercontent.com/assets/23049753/20995431/f3007d1c-bd31-11e6-9c11-f8c82411df60.png)

**Comment by tbarbette** [comment]
Sorry but you got the wrong project ;)
