### ISSUE TITLE
fastmetron     Metron support: no

### ISSUE THREAD

**Issue by ligang626** [tbarbette/fastclick#190]
I am using the metron branch of fastmetron
After configure, the display does not support metron
why?

Configuration Summary:
    C Compiler:                  gcc
    C++ Compiler:                g++

    DPDK support:                yes
    Netmap support:              no
    PCAP support:                yes

    Metron support:              no

    PAPI support:                no
    RE2 support:                 no

**Comment by gkatsikas** [comment]
Hi,

First you need to 'git checkout metron'.
Then, apart from DPDK, you need to enable the following parameters through the configure script (see the instructions in the README):

--enable-json --enable-cpu-load --enable-task-stats

Finally, type make to build Metron.

**Comment by ligang626** [comment]
I use this command:./configure RTE_SDK=/stdio/dpdk/ RTE_TARGET=x86_64-native-linuxapp-gcc --enable-multithread --disable-linuxmodule --enable-intel-cpu --enable-user-multithread --verbose CFLAGS="-std=gnu11 -O3" CXXFLAGS="-std=gnu++14 -O3" --disable-dynamic-linking --enable-poll --enable-bound-port-transfer --enable-dpdk --enable-batch --with-netmap=no --enable-zerocopy --enable-dpdk-pool --disable-dpdk-packet --enable-nanotimestamp --enable-all-elements --enable-json --enable-cpu-load --enable-task-stats

But still show that does not support metron
Metron support: no
I am using this download
Git clone -b metron https://github.com/tbarbette/fastclick.git

**Comment by gkatsikas** [comment]
Could you then post the exact output of the configure script?

**Comment by ligang626** [comment]
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for g++... g++
checking for gcc... (cached) gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for sys/types.h... (cached) yes
checking for unistd.h... (cached) yes
checking for stdint.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for endian.h... yes
checking for machine/endian.h... no
checking for byteswap.h... yes
checking for strings.h... (cached) yes
checking for time.h... yes
checking for termio.h... yes
checking for netdb.h... yes
checking for sys/event.h... no
checking for pwd.h... yes
checking for grp.h... yes
checking for execinfo.h... yes
checking for poll.h... yes
checking for dlfcn.h... yes
checking for sys/mman.h... yes
checking for stdlib.h... (cached) yes
checking for sys/param.h... yes
checking for ifaddrs.h... yes
checking for linux/if_tun.h... yes
checking for net/if_dl.h... no
checking for net/if_tap.h... no
checking for net/if_tun.h... no
checking for net/if_types.h... no
checking for net/bpf.h... no
checking for netpacket/packet.h... yes
checking whether the C compiler accepts -W -Wall... yes
checking whether the C compiler accepts -Werror... yes
checking how to run the C preprocessor... gcc -E
checking for inline... inline
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether <new> works... yes
checking whether the C++ compiler understands 'auto'... yes
checking whether the C++ compiler understands constexpr... yes
checking whether the C++ compiler understands rvalue references... yes
checking whether the C++ compiler understands static_assert... yes
checking whether the C++ compiler understands template alias... yes
checking whether the C++ compiler understands #pragma interface... yes
checking how to run the C++ preprocessor... g++ -E
checking for ar... ar
checking for ld... ld
checking for nm... nm
checking for objcopy... objcopy
checking for ranlib... ranlib
checking for strip... strip
checking for library containing pthread_create... -lpthread
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking whether pthread_setaffinity_np is declared... yes
checking for library containing mbg_open_device... no
checking mbgdevio.h usability... no
checking mbgdevio.h presence... no
checking for mbgdevio.h... no
checking for library containing MHD_start_daemon... no
checking microhttpd.h usability... no
checking microhttpd.h presence... no
checking for microhttpd.h... no
checking for main in -lre2... no
checking re2/re2.h usability... no
checking re2/re2.h presence... no
checking for re2/re2.h... no
checking for library containing PAPI_start_counters... no
checking papi.h usability... no
checking papi.h presence... no
checking for papi.h... no
checking for library containing curl_global_init... no
checking curl/curl.h usability... no
checking curl/curl.h presence... no
checking for curl/curl.h... no
checking whether we are compiling for Linux... yes
checking for strerror... yes
checking for random... yes
checking for snprintf... yes
checking for strnlen... yes
checking for strtof... yes
checking for strtold... yes
checking for strtoul... yes
checking for tcgetpgrp... yes
checking for vsnprintf... yes
checking for aligned_alloc... yes
checking size of int... 4
checking size of long... 8
checking size of size_t... 8
checking size of ptrdiff_t... 8
checking size of void *... 8
checking whether char is unsigned... no
checking whether machine is indifferent to alignment... yes
checking size of long long... 8
checking for long long... yes
checking for int64_t... yes
checking for uint64_t... yes
checking whether long and int64_t are the same type... yes
checking whether long long and int64_t are the same type... no
checking whether byte ordering is bigendian... no
checking whether signed right shift is arithmetic... yes
checking for addressable va_list type... no
checking for __builtin_clz... yes
checking for __builtin_clzl... yes
checking for __builtin_clzll... yes
checking for __builtin_ffs... yes
checking for __builtin_ffsl... yes
checking for __builtin_ffsll... yes
checking for __sync_synchronize... yes
checking whether __sync_synchronize supports arguments... no
checking for __has_trivial_copy... yes
checking for __thread storage class support... yes
checking for ffs... yes
checking for ffsl... yes
checking for ffsll... yes
checking size of struct timeval... 16
checking for struct timespec... yes
checking size of struct timespec... 16
checking whether clock_gettime is declared... yes
checking for library containing clock_gettime... none required
checking for clock_gettime... yes
checking whether <poll.h> is emulated... no
checking for pselect... yes
checking for sigaction... yes
checking for kqueue... no
checking for library containing gethostbyname... none required
checking for library containing connect... none required
checking whether accept() uses socklen_t... yes
checking for large file support in C library... yes
checking size of off_t... 8
checking for getpagesize... yes
checking for working mmap... yes
checking for madvise... yes
checking whether madvise is declared... yes
checking for pcap.h... found
checking whether pcap.h works... yes
checking for bpf_timeval in pcap.h... no
checking whether pcap_setnonblock is declared... yes
checking for -lpcap... found
checking for pcap_inject... yes
checking for pcap_sendpacket... yes
checking for pcap_setdirection... yes
checking for pcap_setnonblock... yes
checking for pcap_set_immediate_mode... yes
checking for library containing numa_available... -lnuma
checking for net/netmap.h... not found
checking whether struct if_data has ifi_datalen... no
checking whether struct sockaddr_in has sin_len... no
checking expat.h usability... yes
checking expat.h presence... yes
checking for expat.h... yes
checking for XML_ParserCreateNS in -lexpat... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether install accepts -C... yes
checking for GNU make... make
checking for working autoconf... found
checking for perl5... no
checking for perl... perl
checking for gawk... gawk
checking for grep that handles long lines and -e... (cached) /bin/grep
checking for egrep... (cached) /bin/grep -E
checking for md5sum... md5sum
checking for working makeinfo... missing
checking for working texi2dvi... missing
checking for install-info... /usr/bin/install-info
checking for working install-info... found
checking for working pod2man... found
configure: creating ./config.status
config.status: creating Makefile
config.status: creating bin/click-buildtool
config.status: creating bin/click-compile
config.status: creating installch
config.status: creating share/click/config.mk
config.status: creating share/click/pkg-config.mk
config.status: creating doc/Makefile
config.status: creating etc/libclick/Makefile
config.status: creating tools/Makefile
config.status: creating tools/lib/Makefile
config.status: creating bsdmodule/Makefile
config.status: creating linuxmodule/Makefile
config.status: creating minios/Makefile
config.status: creating minios/config.mk
config.status: creating ns/Makefile
config.status: creating userlevel/Makefile
config.status: creating tools/click-align/Makefile
config.status: creating tools/click-check/Makefile
config.status: creating tools/click-combine/Makefile
config.status: creating tools/click-devirtualize/Makefile
config.status: creating tools/click-fastclassifier/Makefile
config.status: creating tools/click-flatten/Makefile
config.status: creating tools/click-install/Makefile
config.status: creating tools/click-mkmindriver/Makefile
config.status: creating tools/click-pretty/Makefile
config.status: creating tools/click-undead/Makefile
config.status: creating tools/click-xform/Makefile
config.status: creating tools/click2xml/Makefile
config.status: creating include/click/config.h
config.status: include/click/config.h is unchanged
config.status: creating include/click/pathvars.h
config.status: include/click/pathvars.h is unchanged
config.status: creating include/click/config-bsdmodule.h
config.status: include/click/config-bsdmodule.h is unchanged
config.status: creating include/click/config-linuxmodule.h
config.status: include/click/config-linuxmodule.h is unchanged
config.status: creating include/click/config-ns.h
config.status: include/click/config-ns.h is unchanged
config.status: creating include/click/config-userlevel.h
config.status: include/click/config-userlevel.h is unchanged
config.status: creating include/click/config-minios.h
config.status: include/click/config-minios.h is unchanged


Configuration Summary:
    C Compiler:                  gcc
    C++ Compiler:                g++

    DPDK support:                yes
    Netmap support:              no
    PCAP support:                yes

    Metron support:              no

    PAPI support:                no
    RE2 support:                 no


Metron requires to configure with --enable-json and --enable-cpu-load and install libcurl and libmicrohttpd.
To install libmicrohttpd in a Debian-based OS, type: sudo apt install libmicrohttpd-dev
To install libcurl in a Debian-based OS, type: sudo apt install libcurl4-openssl-dev

**Comment by gkatsikas** [comment]
Please see the last 2 lines of the above message. The configure script gives you instructions on how to install libcurl and libmicrohttpd libraries on your system.

For Debian-based Linux systems you need to type:
1) sudo apt install libmicrohttpd-dev
2) sudo apt install libcurl4-openssl-dev

**Comment by ligang626** [comment]
Thanks
