### ISSUE TITLE
Error when starting :Assertion `(unsigned) i < (unsigned)

### ISSUE THREAD

**Issue by ligang626** [tbarbette/fastclick#192]
use this cmd:bin/click --dpdk -c 0x03 -v -- conf/metron/metron-flow-director.click

EAL: Detected 48 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: RTE Version: 'DPDK 18.05.0'
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:01:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
CPU 0 to 0
lcore 1 deactivated
CPU 1 to 2
CPU 2 to 3
click: ../include/click/vector.hh:291: T& Vector<T>::operator[](Vector<T>::size_type) [with T = int; Vector<T>::size_type = int]: Assertion `(unsigned) i < (unsigned) vm_.n_' failed.
Aborted (core dumped)

**Comment by tbarbette** [comment]
Pretty sure it's caused by the NUMA layout. Can you try -l 0,2,4,6  instead of -c 0x3. I'll try on a 0,1,0,... NUMA machine.

**Comment by tbarbette** [comment]
I can't reproduce without the GDB stack... Works fine with both NUMA layouts here, DPDK 18.05 and .11. It may simply due to the existing but not correct port.
