### ISSUE TITLE
Using stdout in elements code

### ISSUE THREAD

**Issue by reuvenperetz** [tbarbette/fastclick#196]
Hi,
I have some general question, and I hope it's okay doing it here :)

I wrote some element, and it seems to work great, but when I try to print a line or two (using std:cout) for each packet the element processes, I have a really bad packet loss issue.
When I look at the FromDPDKDevice xstats, I can see that there are many rx_mbuf_allocation_errors (when I comment out these printing lines, rx_mbuf_allocation_errors is usually 0 or some negligible number, and I don't suffer from any packet loss).

Maybe that's okay, and this is what I should expect for, but I was wondering if there is a reasonable cause for that?
Thanks!

**Comment by gkatsikas** [comment]
Hi,

This is normal as printing content for each and every packet consumes a lot of CPU. Printing is mostly meant for debugging and error handling purposes, therefore I suggest to remove all print commands from the "fast path". Moreover, Click provides it's own printing facilities so you could replace std:cout/cerr with ErrorHandler instances (using info/message/error methods) or click_chatter.

**Comment by reuvenperetz** [comment]
Thanks, Georgios and Tom!
That's actually the kind of thing I thought might be the problem because I had a similar issue when trying to log to a file.
Tom, you wrote "logging to a file is challenging at very high speed. Eg to write packets at 100G".
It happened to me even when the element processed relatively low packets rate (~100K packets/second. Or at least I think it's a pretty low rate).
Would you expect it to happen even in such rate? I know that there are probably many other parameters that should be taken into account when answering about that, but I'm trying to understand how the packet rate may affect the loss rate, because I had almost 90% packet loss, and it seemed not proportional to me at first sight.

**Comment by tbarbette** [comment]
Yes, 100K is a huge number of prints per seconds. One easy way to know what slow down to expect would be to do a for loop with a print of a number inside it... Then you'll have your system's print capacity. Though I think the best would be to check if you really want to do this? What do you want to log? You'll probably have to use multi-threading for this.

**Comment by reuvenperetz** [comment]
Thanks, you pretty much approved many things I speculated :)
What I'm doing is giving each packet an ID and track which IDs went through the Click process, so what I eventually did is to keep that data in memory and another newly created thread is taking care of it (in a producer-consumer way).
I thought it might be the problem, and didn't know exactly how to explain it (this is why I opened this issue), but I saw that it solved it, so now this is how I do it.
Thanks a lot for helping me understand it better, I think the issue can be closed now :)
