### ISSUE TITLE
DPDK 16.11 and beyond

### ISSUE THREAD

**Issue by gkatsikas** [tbarbette/fastclick#21]
Hi Tom,

Is there a plan to update FastClick and make it compatible with the latest DPDK version 16.11 (soon 17 is coming)?
I would like to test a Mellanox 100GbE board using FastClick.

Best regards,
Georgios

**Comment by tbarbette** [comment]
Yeah, it's already done on my testing branch ;) Just the time to check that and merge.

**Comment by gkatsikas** [comment]
Cool, thanks ;)
