### ISSUE TITLE
Compilation error with "cannot find -lgcc_s"

### ISSUE THREAD

**Issue by aquatoney** [tbarbette/fastclick#238]
Hi,

I clone the latest commit from the master branch and follow the installation instructions.
Here's my command:

`./configure --enable-multithread --disable-linuxmodule --enable-intel-cpu --enable-user-multithread --verbose CFLAGS="-g -O3 -mssse3" CXXFLAGS="-g -std=gnu++11 -O3 -mssse3" --disable-dynamic-linking --enable-poll --enable-bound-port-transfer --enable-dpdk --enable-batch --with-netmap=no --enable-zerocopy --disable-dpdk-pool --disable-dpdk-packet`

`make`

Then I got the following error

`/usr/bin/ld: cannot find -lgcc_s`

I've confirmed that I have `/lib/x86_64-linux-gnu/libgcc_s.so.1` which is linked from
`/usr/lib/gcc/x86_64-linux-gnu/7/libgcc_s.so.1`.

Any ideas to solve this problem?

My gcc version is 7.40, DPDK version is 18.04.

BTW, I have to add `-mssse3` into the CFLAGS and CXXFLAGS (shown above), or the inline assemble functions would raise errors. I'm using Intel Xeon CPUs (Broadwell).

**Comment by tbarbette** [comment]
Hi @aquatoney !

Which OS? Ubuntu? The ssse is weird. I would actually add -march=native instead. Actually that should be the default...

Can you show the outpot of make V=1 also?

Thanks,

Tom

**Comment by aquatoney** [comment]
Hi Tom,

Thanks for your quick response.

I'm using Ubuntu server 18.04 LTS.

For the SSE problem, adding -march=native does solve the error, so maybe some default
settings are broken of my gcc. 

Here's the output of make V=1.

Many g++ lines for compiling elements are omitted here
`g++ -DHAVE_CONFIG_H -I../include -I../vendor -I../include -I. -I..  -D__MTCLICK__ -DCLICK_USERLEVEL -g -O3 -march=native -Wno-pmf-conversions -include /usr/include/x86_64-linux-gnu/dpdk/rte_config.h -I/usr/include/x86_64-linux-gnu/dpdk -I/usr/include/dpdk -include /usr/include/x86_64-linux-gnu/dpdk/rte_config.h -I/usr/include/x86_64-linux-gnu/dpdk -I/usr/include/dpdk  -c ../elements/userlevel/umlswitch.cc -o umlswitch.o
../bin/click-buildtool elem2export < elements.conf > elements.cc
g++ -DHAVE_CONFIG_H -I../include -I../vendor -I../include -I. -I..  -D__MTCLICK__ -DCLICK_USERLEVEL -g -O3 -march=native -Wno-pmf-conversions -include /usr/include/x86_64-linux-gnu/dpdk/rte_config.h -I/usr/include/x86_64-linux-gnu/dpdk -I/usr/include/dpdk -include /usr/include/x86_64-linux-gnu/dpdk/rte_config.h -I/usr/include/x86_64-linux-gnu/dpdk -I/usr/include/dpdk  -c elements.cc -o elements.o
g++ -DHAVE_CONFIG_H -I../include -I../vendor -I../include -I. -I..  -D__MTCLICK__ -DCLICK_USERLEVEL -g -O3 -march=native -Wno-pmf-conversions -include /usr/include/x86_64-linux-gnu/dpdk/rte_config.h -I/usr/include/x86_64-linux-gnu/dpdk -I/usr/include/dpdk -include /usr/include/x86_64-linux-gnu/dpdk/rte_config.h -I/usr/include/x86_64-linux-gnu/dpdk -I/usr/include/dpdk  -c click.cc -o click.o
g++ -g -O3 -march=native -Wno-pmf-conversions -include /usr/include/x86_64-linux-gnu/dpdk/rte_config.h -I/usr/include/x86_64-linux-gnu/dpdk -I/usr/include/dpdk -include /usr/include/x86_64-linux-gnu/dpdk/rte_config.h -I/usr/include/x86_64-linux-gnu/dpdk -I/usr/include/dpdk -Lnuma -lrte_acl -lrte_bitratestats -lrte_bus_pci -lrte_bus_vdev -lrte_cfgfile -lrte_cmdline -lrte_cryptodev -lrte_distributor -lrte_eal -lrte_efd -lrte_ethdev -lrte_eventdev -lrte_flow_classify -lrte_gro -lrte_gso -lrte_hash -lrte_ip_frag -lrte_jobstats -lrte_kni -lrte_kvargs -lrte_latencystats -lrte_lpm -lrte_mbuf -lrte_member -lrte_mempool -lrte_mempool_octeontx -lrte_mempool_ring -lrte_mempool_stack -lrte_meter -lrte_metrics -lrte_net -lrte_pci -lrte_pdump -lrte_pipeline -lrte_pmd_af_packet -lrte_pmd_ark -lrte_pmd_avp -lrte_pmd_bnxt -lrte_pmd_bond -lrte_pmd_crypto_scheduler -lrte_pmd_cxgbe -lrte_pmd_e1000 -lrte_pmd_ena -lrte_pmd_enic -lrte_pmd_failsafe -lrte_pmd_fm10k -lrte_pmd_i40e -lrte_pmd_ixgbe -lrte_pmd_kni -lrte_pmd_lio -lrte_pmd_mlx4 -lrte_pmd_mlx5 -lrte_pmd_nfp -lrte_pmd_null -lrte_pmd_null_crypto -lrte_pmd_octeontx -lrte_pmd_octeontx_ssovf -lrte_pmd_pcap -lrte_pmd_qede -lrte_pmd_ring -lrte_pmd_sfc_efx -lrte_pmd_skeleton_event -lrte_pmd_softnic -lrte_pmd_sw_event -lrte_pmd_tap -lrte_pmd_thunderx_nicvf -lrte_pmd_vhost -lrte_pmd_virtio -lrte_pmd_vmxnet3_uio -lrte_port -lrte_power -lrte_reorder -lrte_ring -lrte_sched -lrte_security -lrte_table -lrte_timer -lrte_vhost -ldl -lm -lpthread -lz -Wl,-Bstatic -lrte_acl -lrte_bitratestats -lrte_bus_pci -lrte_bus_vdev -lrte_cfgfile -lrte_cmdline -lrte_cryptodev -lrte_distributor -lrte_eal -lrte_efd -lrte_ethdev -lrte_eventdev -lrte_flow_classify -lrte_gro -lrte_gso -lrte_hash -lrte_ip_frag -lrte_jobstats -lrte_kni -lrte_kvargs -lrte_latencystats -lrte_lpm -lrte_mbuf -lrte_member -lrte_mempool -lrte_mempool_octeontx -lrte_mempool_ring -lrte_mempool_stack -lrte_meter -lrte_metrics -lrte_net -lrte_pci -lrte_pdump -lrte_pipeline -lrte_pmd_af_packet -lrte_pmd_ark -lrte_pmd_avp -lrte_pmd_bnxt -lrte_pmd_bond -lrte_pmd_crypto_scheduler -lrte_pmd_cxgbe -lrte_pmd_e1000 -lrte_pmd_ena -lrte_pmd_enic -lrte_pmd_failsafe -lrte_pmd_fm10k -lrte_pmd_i40e -lrte_pmd_ixgbe -lrte_pmd_kni -lrte_pmd_lio -lrte_pmd_mlx4 -lrte_pmd_mlx5 -lrte_pmd_nfp -lrte_pmd_null -lrte_pmd_null_crypto -lrte_pmd_octeontx -lrte_pmd_octeontx_ssovf -lrte_pmd_pcap -lrte_pmd_qede -lrte_pmd_ring -lrte_pmd_sfc_efx -lrte_pmd_skeleton_event -lrte_pmd_softnic -lrte_pmd_sw_event -lrte_pmd_tap -lrte_pmd_thunderx_nicvf -lrte_pmd_vhost -lrte_pmd_virtio -lrte_pmd_vmxnet3_uio -lrte_port -lrte_power -lrte_reorder -lrte_ring -lrte_sched -lrte_security -lrte_table -lrte_timer -lrte_vhost -ldl -lm -lpthread -lz -o click  adjusttimestamp.o aggcounter.o aggpktcounter.o aggregatefilter.o aggregatefirst.o aggregateip.o aggregateipaddrpair.o aggregateipflows.o aggregatelast.o aggregatelen.o aggregatenotifier.o aggregatepaint.o anonipaddr.o averagebatchcounter.o batchstats.o checknumberpacket.o cyclecountaccum.o eraseippayload.o fromcapdump.o fromdagdump.o fromipsumdump.o fromnetflowsumdump.o fromnlanrdump.o fromtcpdump.o ipsumdump_anno.o ipsumdump_icmp.o ipsumdump_ip.o ipsumdump_link.o ipsumdump_payload.o ipsumdump_tcp.o ipsumdump_udp.o ipsumdumpinfo.o multireplay.o numberpacket.o packetmemstats.o recordtimestamp.o replay.o rtcycles.o setcyclecount.o settimestampdelta.o storetimestamp.o storeudptimeseqrecord.o timefilter.o timerange.o timesortedsched.o timestampaccum.o timestampdiff.o toipflowdumps.o toipsumdump.o  ftpportmapper.o  adaptivered.o codel.o red.o  arpadvertiser.o arpfaker.o arpprint.o arpquerier.o arpresponder.o arptable.o checkarpheader.o ensureether.o etherencap.o ethermirror.o etherpausesource.o etherrewrite.o ethervlanencap.o getetheraddress.o hostetherfilter.o setetheraddress.o setvlananno.o storeetheraddress.o stripethervlanheader.o vlandecap.o vlanencap.o  checkicmpheader.o icmperror.o icmpipencap.o icmppingencap.o icmppingresponder.o icmppingrewriter.o icmprewriter.o icmpsendpings.o  checkipheader.o checkipheader2.o decipttl.o directiplookup.o fixipsrc.o getipaddress.o ipaddrpairrewriter.o ipaddrrewriter.o ipclassifier.o ipencap.o ipfieldinfo.o ipfilter.o ipfragmenter.o ipgwoptions.o ipinputcombo.o ipmirror.o ipnameinfo.o ipoutputcombo.o ipprint.o ipratemon.o ipreassembler.o iprewriterbase.o iprewritermap.o iproutetable.o iprwmapping.o iprwpattern.o iprwpatterns.o lineariplookup.o lookupiproute.o lookupiproutelinux.o lookupiproutemp.o markipce.o markipheader.o radixiplookup.o rangeiplookup.o rfc2507c.o rfc2507d.o ripsend.o rripmapper.o setipaddress.o setipchecksum.o setipdscp.o setipecn.o setrandipaddress.o siphmapper.o sortediplookup.o storeipaddress.o stripipheader.o threadipmapper.o truncateippayload.o unstripipheader.o  simpleidle.o simplepriosched.o simplepullswitch.o simplerrsched.o  align.o annotationinfo.o averagecounter.o bandwidthmeter.o bandwidthshaper.o block.o burster.o bwratedsplitter.o bwratedunqueue.o bypass.o checkcrc32.o checklength.o checkpaint.o classification.o classifier.o clickyinfo.o clipboard.o counter.o cpuqueue.o cpuswitch.o delayshaper.o delayunqueue.o devirtualizeinfo.o discard.o discardnofree.o discardnofreebuffer.o drivermanager.o dropbroadcasts.o drr.o ensureheadroom.o flowinfo.o frontdropqueue.o fullnotequeue.o hashswitch.o hub.o idle.o infinitesource.o inputswitch.o linkunqueue.o markmacheader.o messageelement.o meter.o minbatch.o mixedqueue.o movedata.o msqueue.o notifierqueue.o nullelement.o nulls.o pad.o paint.o paintrr.o paintswitch.o painttee.o pipeliner.o print.o priosched.o pullswitch.o quicknotequeue.o quitwatcher.o randomerror.o randomsample.o randomsource.o randomswitch.o ratedsource.o ratedsplitter.o ratedunqueue.o resize.o rrmultisched.o rrsched.o rrswitch.o script.o setannobyte.o setcrc32.o setpackettype.o settimestamp.o shaper.o simplequeue.o staticpullswitch.o staticswitch.o storedata.o stridesched.o strideswitch.o strip.o striptonet.o suppressor.o switch.o tee.o threadsafequeue.o timedsink.o timedsource.o timedunqueue.o truncate.o unqueue.o unqueue2.o unstrip.o  checktcpheader.o checkudpheader.o dynudpipencap.o fasttcpflows.o fastudpflows.o iploadbalancer.o iprewriter.o resetipchecksum.o settcpchecksum.o setudpchecksum.o striptransportheader.o tcpfragmenter.o tcpipsend.o tcprewriter.o udpipencap.o udprewriter.o unstriptransportheader.o  batchtest.o bhmtest.o biginttest.o bitvectortest.o blockthread.o checkpacket.o clptest.o comparepackets.o confparsetest.o cryptotest.o dequetest.o errortest.o functiontest.o handlertask.o hashtablemptest.o hashtabletest.o heaptest.o listtest.o mtdietest.o neighborhoodtest.o notifierdebug.o notifiertest.o nulltask.o packettest.o queuethreadtest.o queueyanktest.o randomseed.o rcutest.o schedordertest.o sorttest.o stringtest.o taskthreadtest.o timertest.o tokenbuckettest.o upstreamnotifier.o vectortest.o  pathspinlock.o spinlockacquire.o spinlockinfo.o spinlockrelease.o staticthreadsched.o  changeuid.o chattersocket.o controlsocket.o counterfile.o dpdkinfo.o ensuredpdkbuffer.o fakepcap.o fastudpsrc.o fromdevice.o fromdpdkdevice.o fromdpdkring.o fromdump.o fromhost.o fromrawsocket.o fromsocket.o handlerproxy.o ipflowrawsockets.o kernelfilter.o kerneltap.o kerneltun.o khandlerproxy.o mcastsocket.o monitoringreportsocket.o progressbar.o queuedevice.o rawsocket.o socket.o todevice.o todpdkdevice.o todpdkring.o todump.o tohost.o torawsocket.o tosocket.o umlswitch.o   elements.o click.o libclick.a -lnuma  -lre2 `../bin/click-buildtool --otherlibs`  
/usr/bin/ld: cannot find -lgcc_s
libclick.a(args.o): In function `FilenameArg::parse(String const&, String&, ArgContext const&)':
/home/toney/Projects/fastclick/userlevel/../lib/args.cc:1368: warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnuma.a(affinity.o): In function `affinity_ip':
(.text+0x775): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
monitoringreportsocket.o: In function `MonitoringReportSocket::initialize(ErrorHandler*)':
/home/toney/Projects/fastclick/userlevel/../elements/userlevel/monitoringreportsocket.cc:248: warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpcap.a(nametoaddr.o): In function `pcap_nametonetaddr':
(.text+0xc5): warning: Using 'getnetbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
ipnameinfo.o: In function `(anonymous namespace)::ServicesNameDB::query(String const&, void*, unsigned long)':
/home/toney/Projects/fastclick/userlevel/../elements/ip/ipnameinfo.cc:340: warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/toney/Projects/fastclick/userlevel/../elements/ip/ipnameinfo.cc:324: warning: Using 'getprotobyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/toney/Projects/fastclick/userlevel/../elements/ip/ipnameinfo.cc:344: warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
Makefile:148: recipe for target 'click' failed
make[1]: *** [click] Error 1
make[1]: Leaving directory '/home/toney/Projects/fastclick/userlevel'
Makefile:57: recipe for target 'userlevel' failed
make: *** [userlevel] Error 2
`

Thanks in advance.
Hao

**Comment by tbarbette** [comment]
I've never seen that error. There is something weird with your environment. The fact that the default arch refuse SSE instructions hint something abnormal with your GCC... Is there something specific you would have done in your environment you could think of?
Also can you try to add --enable-userlevel specifically? Just to be sure.

**Comment by tbarbette** [comment]
Also did you look a bit at that linking error? Chances are it's not FastClick specific. Eg https://askubuntu.com/questions/346377/cannot-find-lgcc-s ?

**Comment by aquatoney** [comment]
Hi Tom,

1) Yes I think the SSE problem should due to some environmental issues on my server. 
I will try to add --enable--userlevel later for confirmation. Anyway, adding -mssse3 or -march=native solves the problem, so it is fine with me. 

2) Thanks for your link. Actually I've googled a lot before opening this issue, and most 
resolutions indicate that the problem is due to the lost of libgcc_s.so. 
However, I've confirmed that I have a correct .so file in the correct directory.

I also tried to compile FastClick in a newly installed Ubuntu VM, still the same problem.
I will try some minimal working examples with gcc_s to pin the problem.

Will get back to you if I have some new findings.

Again, thanks for your help!

**Comment by aquatoney** [comment]
Hi Tom,

I finally make it work.
Apparently, other people who use this machine have installed DPDK system-widely, so there are some 17.11 files in the local include and lib directories.
These files seem to make conflicts with the specified RTE_SDK (which is 18.11) and produce some weird errors.

After I clean up the system-wide files (.a, .so and .h), I succeed to make this project.

This issue can be closed, but I'm afraid I will soon open another one about the configuration of 
fastclick, (actually more about the middleclick branch).

Thanks!
Hao
