### ISSUE TITLE
MiddleClick configurations

### ISSUE THREAD

**Issue by aquatoney** [tbarbette/fastclick#239]
Hi Tom,

I've switched to middleclick branch, and use the configure command (the long version with DPDK enabled) to make the project. I have tried the configuration provided in conf/middleclick/,
but none of them seems to work. For example, 

`sudo bin/click --dpdk -c 0xf -n 4 -w 04:00.0 -w 04:00.1 -- conf/middleclick/middlebox-ip-empty.click`

gives me

EAL: Detected 40 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:04:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1583 net_i40e
EAL: PCI device 0000:04:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1583 net_i40e
conf/middleclick/middlebox-ip-empty.click:15: undeclared element ‘TSCClock’
conf/middleclick/middlebox-ip-empty.click:18: undeclared element ‘JiffieClock’
conf/middleclick/middlebox-ip-empty.click:23: unknown element class ‘FlowDispatcher’
conf/middleclick/middlebox-ip-empty.click:49: unknown element class ‘FlowClassifier’
conf/middleclick/middlebox-ip-empty.click:53: undeclared element ‘FlowStrip’
conf/middleclick/middlebox-ip-empty.click:55: unknown element class ‘FlowDispatcher’

The other firewall.click also reports the errors that some elements are not defined. 
Is there anything wrong with my process?

BTW, I've also tried the minimal example in Wiki, i.e., 

`FromDPDKDevice(0) -> CheckIPHeader(OFFSET 14) -> ToDPDKDevice(1)`

which does not produce any error, but stucks with showing "Initilizing DPDK". 
Is it an expected behavior?

Thanks in advance.
Hao

**Comment by aquatoney** [comment]
Hi Tom,

I went to middleclick-experiment repo and found some clues.
Now I add --enable-flow and --enable-user-level-timestamp to configure, and most elements can be compiled, but still FlowClassifier is not found. 
"--enable-all-elements" also seems not to work.

Any suggestion?

**Comment by tbarbette** [comment]
Sorry, I recently renamed FlowClassifier in FlowManager and forgot the config file. I pushed a commit. Should be fixed.

Don't hesitate to continue asking questions ;) I need a push to build the documentation...

**Comment by aquatoney** [comment]
Thanks for the quick fix!

With the fix, middlebox-ip-empty.click almost works, except two errors:

conf/middleclick/middlebox-ip-empty.click:15: ‘TSCClock@1 :: TSCClock’ input 0 unused
conf/middleclick/middlebox-ip-empty.click:15: ‘TSCClock@1 :: TSCClock’ output 0 unused

If I comment line 15 (`TSCClock(NOWAIT true)`), everything seems to work. 
Still try to figure out the inner logic of the configuration (I'm new to Click).

BTW, I saw your updated Readme, there are two issues of the new configure command
(1) it should be `--enable-user-timestamp` instead of `--enable-user-level-timestamp`
(2) `--enable-ctx` is not recognized by the configure file.

So I guess the configuration file also needs to be updated?

Again, thanks for your kindly help. This is a very interesting work, and it would be great if
we can keep discussing it. Both email and issue tracker would do.

**Comment by tbarbette** [comment]
Mhh again a too fast update. TSCClock can also convert packet time and do not need ports, it's fixed now. I would suggest keeping it commented until you strike for the last percentage of performance.

Correct for the options name too. --enable-ctx will come later. I must move elements according to the context and flow ones to different folders.

**Comment by tbarbette** [comment]
A mininet and a new more evolved configuration is provided now :)
