### ISSUE TITLE
Check DPDK Flow rule installation/deletion

### ISSUE THREAD

**Issue by gkatsikas** [tbarbette/fastclick#250]
Cross check the code using the new app/test-flow-perf from DPDK:

https://www.mail-archive.com/dev@dpdk.org/msg163432.html

Also, keep this in mind:

https://www.mail-archive.com/users@dpdk.org/msg04800.html

**Comment by gkatsikas** [comment]
Metron rule management engine is slower than DPDK's flow-perf tool for a good reason.
Any rule that Metron attempts to install goes through a validation process and a FlowRuleCache which manages the runtime behavior of a Metron NIC, especially for load balancing purposes.

**Comment by tbarbette** [comment]
Maybe the solution is to make Metron's cache lighter. The rules are always cached by DPDK itself anyway and have a traversal system already.
