### ISSUE TITLE
How do I include DDIOTune?

### ISSUE THREAD

**Issue by rudh24** [tbarbette/fastclick#270]
Hi Tom,

I was hoping to make use of the DDIOTune element to disable DDIO. However I can't find a way to include the DDIOTune element.
I configured the Makefiles with the `--enable-research` flag which gets me few of the research elements but not DDIO. Any pointers on how I can proceed?

Many thanks,
Anirudh

**Comment by aliireza** [comment]
Hi Anirudh,

DDIOTune requires '--enable-dpdk' and '--enable-research'. 
Please make sure that you have installed `libpci-dev` libraries. 

Cheers,
Alireza

**Comment by rudh24** [comment]
Thanks for the quick response Alireza!
What version do you recommend for the `libpci-dev` libraries. 
I installed the `1:3.3.1-1.1ubuntu1.3` version but I haven't been able to build successfully.
```
../elements/research/ddiotune.cc: In member function 'pci_dev* DDIOTune::find_ddio_device(uint8_t)':
../elements/research/ddiotune.cc:79:58: error: 'PCI_FILL_NUMA_NODE' was not declared in this scope
     pci_fill_info(dev, PCI_FILL_IDENT | PCI_FILL_BASES | PCI_FILL_NUMA_NODE |
                                                          ^
../elements/research/ddiotune.cc: In member function 'virtual int DDIOTune::initialize(ErrorHandler*)':
../elements/research/ddiotune.cc:254:22: error: 'struct pci_dev' has no member named 'numa_node'
   _numa_node = _dev->numa_node;
                      ^
../elements/research/ddiotune.cc:272:51: error: '__get_cpuid_count' was not declared in this scope
     __get_cpuid_count(4, i, &eax, &ebx, &ecx, &edx);

```

**Comment by aliireza** [comment]
I have `libpci-dev/bionic-updates,now 1:3.5.2-1ubuntu1.1 amd64` and it works. 
Can you check whether you have `cpuid` installed or not? Try: `sudo apt-get install cpuid`
What compiler are you using?

**Comment by rudh24** [comment]
I am running Ubuntu 16.04.6 LTS (Xenial Xerus)
The compiler is: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
I managed to fix the numa_node issue using the [`pciutils`](http://mj.ucw.cz/sw/pciutils/) package. However I still have the following error:
```
../elements/research/ddiotune.cc:272:51: error: '__get_cpuid_count' was not declared in this scope
     __get_cpuid_count(4, i, &eax, &ebx, &ecx, &edx);
```

I have `cpuid` installed, however `cpuid.h` doesn't have the `__get_cpuid_count()` function.
Should I be using the clang compiler?

**Comment by aliireza** [comment]
Great! 
I'll note the dependencies in my repository. Thanks :)

**Comment by rudh24** [comment]
Hi Alireza,

Apologies. I've come across a new issue. (Let me know if I should create a new one to address this)

I see that ddiotune.cc makes use of DPDK EAL library and includes rte_lcore.h
It retrieves the `numa_node` for each core using [`rte_lcore_to_socket_id()`](https://github.com/tbarbette/fastclick/blob/e02e38ffe54d345089dd1cfbe61c105a74390126/elements/research/ddiotune.cc#L258)

For some reason, this **returns 0 for every core on my system.**

I have installed `dpdk-stable-19.11.3`. 
Have you come across this? I suspect it could be a versioning issue. could you also tell me the DPDK version? 

Many thanks,
Anirudh

**Comment by aliireza** [comment]
If your system has only one CPU socket, it should return 0 for all of the cores. You can double-check this via `lscpu` command. It prints the number of NUMA nodes and the mapping between cores & nodes.
