### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by p4pe** [tbarbette/fastclick#284]
Hello,

I'm trying to install fastclick, with the following configuration:
`./configure --enable-dpdk --enable-multithread --disable-linuxmodule --enable-intel-cpu --enable-user-multithread --verbose --enable-select=poll CFLAGS="-O3" CXXFLAGS="-std=c++11 -O3"  --disable-dynamic-linking --enable-poll --enable-bound-port-transfer --enable-local --enable-flow --disable-task-stats --disable-cpu-load
`

But during the make install proccess I had the following errors:

![issue1](https://user-images.githubusercontent.com/35313995/99955997-ef198d80-2d8d-11eb-8e39-f6b9c9f2c771.png)

![issue2](https://user-images.githubusercontent.com/35313995/99956008-f2ad1480-2d8d-11eb-8f3b-f44cd9d91403.png)

Thank you in advance

**Comment by tbarbette** [comment]
Click is correctly compiled in userlevel/click, you may use it directly.
The installation fails because you miss the perl which module, try maybe perl -MCPAN -e which. I should detect that automatically though...
Cheers,
Tom
