### ISSUE TITLE
./configure should enable AVX2 depending on CPU, not compiler

### ISSUE THREAD

**Issue by SolalPirelli** [tbarbette/fastclick#310]
First, this project is cool, thanks for creating it. :-)

On my Ivy Bridge machine with GCC 10, `./configure` enables AVX2 by default, which leads to an `Illegal instruction` crash when running Click. This seems to be because it tests whether the compiler supports the `-mavx2` flag and the intrinsics headers, but not whether these flags can actually be used on the current machine (i.e., `-march=native`). So I have to explicitly `--disable-avx2`.

**Comment by tbarbette** [comment]
Ha yes! I took a shortcut on that one... I should test the execution like any header check etc. Hopefully, you have a fix meanwhile :)

**Comment by SolalPirelli** [comment]
I have zero knowledge of autoconf so I can't help there, sorry :(

But `gcc -march=native -dM -E - < /dev/null | grep -q 'AVX2'` returns 0 if AVX2 is supported and 1 otherwise, so that can be used in a script to pass `--disable-avx2` to `./configure` or not.

**Comment by tbarbette** [comment]
Thanks! Turns out there was a built-in configure feature :)

**Comment by SolalPirelli** [comment]
Thanks for the quick fix!
