### ISSUE TITLE
Problem with XL710 Intel NIC

### ISSUE THREAD

**Issue by sarsanaee** [tbarbette/fastclick#320]
Hey, 

I'd like to test fastclick with `XL710 Intel NIC`. However, something seems to be wrong. It actually works properly with `Mellanox ConnectX-4 Lx`.

Here is the error, I'm getting:
```
conf/dpdk/dpdk-bounce.click:11: While initializing ‘FromDPDKDevice@1 :: FromDPDKDevice’:
  The number of receive descriptors is 100 but needs to be between 0 and 0
Router could not be initialized!
```

I don't understand why it expects 0 for the receive descriptors! It is just the simplest script,`dpdk-bounce.click`.

Thanks

**Comment by sarsanaee** [comment]
I believe the issue is coming from here.

https://github.com/tbarbette/fastclick/blob/69d731ec18ecb8d3b5388719f6d143dffa5c6958/lib/dpdkdevice.cc#L594

We are expecting the `rte_eth_dev_info_get` to fill `dev_info` no? Is it a driver issue then?

Thanks,
Alireza

**Comment by tbarbette** [comment]
Hi!
Yes it seems there's actually no guarantee these fields are filled by the driver. I'll add a condition.
It's weird the driver does not set it though... I did use XL710 and did not have that problem. Are you using VFs or something specific about the driver? Which DPDK version?
Tom

**Comment by sarsanaee** [comment]
Hi Tom,

Thank you for the reply.

No, I don't use VFs.

I loaded igb_uio downloaded from kmod repository. DPDK version is 20.10.

Thanks,
Alireza

**Comment by magaboomchen** [comment]
Hi!
I meet a similar problem with XL710.
I just run a simple L2-fwd click using DPDK. Then FastClick reports:
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:05:02.0 on NUMA socket 0
EAL:   probe driver: 8086:154c net_i40e_vf
Initializing DPDK
i40evf_dev_configure(): VF can't disable HW CRC Strip
/home/user/l2fwd.click:2: While initializing ‘out0 :: ToDPDKDevice’:
  Cannot initialize DPDK port 0 with 1 RX and 1 TX queues
  Error -22 : Unknown error -22
Router could not be initialized!

Here is my click conf:
in0 :: FromDPDKDevice(0);
out0 :: ToDPDKDevice(0);
in0 -> EtherMirror() -> out0;

And here is the driver of XL710:
driver: i40e
version: 1.4.25-k
firmware-version: 5.05 0x80002924 1.1313.0
expansion-rom-version: 
bus-info: 0000:05:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

I do use the VFs and there is no problem when I use PF.
Thanks!

**Comment by sarsanaee** [comment]
Hi @magaboomchen 

Had you pulled the repository, since we closed this issue? He pushed a change, that I suppose would solve your problem.

**Comment by magaboomchen** [comment]
Thanks!
I pulled the repository and change the version of DPDK to 20.11.1.
Now, everything is ok!
By the way, I can't build the FastClick using DPDK 18.05 because of the "ret_flow_isolate()" function.
Thanks again!

**Comment by tbarbette** [comment]
Yes sorry it was a small regression introduced recently. We did use XL710, 82599 and Connect-X 4 to 6,  and BlueField recently so all of those are working. But all DPDK ones should work of course.

@magaboomchen  did you keep the error log by any chance? With github actions I only test the recent DPDK versions, so it's probably a regression too, should be easy to fix if you have the error line.
