### ISSUE TITLE
Build error for source files under tools/lib

### ISSUE THREAD

**Issue by GrehXscape** [tbarbette/fastclick#325]
```
make[1]: Entering directory `/home/eric/fastclick/fastclick-master/tools'
make[2]: Entering directory `/home/eric/fastclick/fastclick-master/tools/lib'
  CXX ../../lib/string.cc
make[2]: [string.o] Error 1 (ignored)
  CXX ../../lib/straccum.cc
make[2]: [straccum.o] Error 1 (ignored)
  CXX ../../lib/glue.cc
make[2]: [glue.o] Error 1 (ignored)
  CXX ../../lib/bitvector.cc
make[2]: [bitvector.o] Error 1 (ignored)
  CXX ../../lib/hashallocator.cc
make[2]: [hashallocator.o] Error 1 (ignored)
  CXX ../../lib/ipaddress.cc
make[2]: [ipaddress.o] Error 1 (ignored)
  CXX ../../lib/etheraddress.cc
make[2]: [etheraddress.o] Error 1 (ignored)
  CXX ../../lib/timestamp.cc
make[2]: [timestamp.o] Error 1 (ignored)
  CXX ../../lib/error.cc
make[2]: [error.o] Error 1 (ignored)
  CXX elementt.cc
make[2]: [elementt.o] Error 1 (ignored)
  CXX eclasst.cc
make[2]: [eclasst.o] Error 1 (ignored)
  CXX routert.cc
make[2]: [routert.o] Error 1 (ignored)
  CXX runparse.cc
make[2]: [runparse.o] Error 1 (ignored)
  CXX ../../lib/variableenv.cc
make[2]: [variableenv.o] Error 1 (ignored)
  CXX landmarkt.cc
make[2]: [landmarkt.o] Error 1 (ignored)
  CXX lexert.cc
make[2]: [lexert.o] Error 1 (ignored)
  CXX lexertinfo.cc
make[2]: [lexertinfo.o] Error 1 (ignored)
  CXX ../../lib/driver.cc
make[2]: [driver.o] Error 1 (ignored)
  CXX ../../lib/confparse.cc
make[2]: [confparse.o] Error 1 (ignored)
  CXX ../../lib/args.cc
make[2]: [args.o] Error 1 (ignored)
  CXX ../../lib/archive.cc
make[2]: [archive.o] Error 1 (ignored)
  CXX processingt.cc
make[2]: [processingt.o] Error 1 (ignored)
  CXX etraits.cc
make[2]: [etraits.o] Error 1 (ignored)
  CXX elementmap.cc
make[2]: [elementmap.o] Error 1 (ignored)
  CXX ../../lib/userutils.cc
make[2]: [userutils.o] Error 1 (ignored)
  CXX ../../lib/md5.cc
make[2]: [md5.o] Error 1 (ignored)
  CXX toolutils.cc
make[2]: [toolutils.o] Error 1 (ignored)
  CC ../../lib/clp.c
make[2]: [clp.o] Error 1 (ignored)
  AR libclicktool.a
  RANLIB libclicktool.a
make[2]: Leaving directory `/home/eric/fastclick/fastclick-master/tools/lib'

```
Error occurs while compling tools/lib with both master and v19.11 release version.

**Comment by tbarbette** [comment]
Hi! Yes it's actually in Click too. I've had that at the first build since years, but everything still actually works... Click is built correctly right? I'm not sure what causes that but given it works, I never took the time to look into it...

**Comment by GrehXscape** [comment]
> Hi! Yes it's actually in Click too. I've had that at the first build since years, but everything still actually works... Click is built correctly right? I'm not sure what causes that but given it works, I never took the time to look into it... I'll do now.

Thank you for your help. I'm a beginner, and this is my first time to use fastclick or even click. How can I do a quick check to see if the fastclick runs properly?

**Comment by tbarbette** [comment]
make && ./userlevel/click -e "DriverManager(print 'Hello World!');"

**Comment by tbarbette** [comment]
This error appears when using parallel compilation, but is clearly a false negative. I can't find why it happens though. GCC gives no errors.

**Comment by GrehXscape** [comment]
I can run the basic click function now, but as for dpdk, I wrote a simple script following the wiki on high speed I/O.
`FromDPDKDevice(0) -> CheckIPHeader(OFFSET 14) -> ToDPDKDevice(1)`
And ran it with
`sudo ~/fastclick/fastclick-master/bin/click --dpdk -c 0xf -n 4 -- ./test.click`
But it turns out that fastclick couldn't find the NIC ports which I've already bind with igb_uio and could be detected with dpdk-20.11 apps like testpmd.

```
Network devices using DPDK-compatible driver
============================================
0000:01:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection 10fb' drv=igb_uio unused=ixgbe,uio_pci_generic
0000:01:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection 10fb' drv=igb_uio unused=ixgbe,uio_pci_generic
0000:06:00.0 'I210 Gigabit Network Connection 1533' drv=igb_uio unused=igb,uio_pci_generic

Network devices using kernel driver
===================================
0000:05:00.0 'I210 Gigabit Network Connection 1533' if=eno1 drv=igb unused=igb_uio,uio_pci_generic *Active*

No 'Baseband' devices detected
==============================

No 'Crypto' devices detected
============================

No 'Eventdev' devices detected
==============================

No 'Mempool' devices detected
=============================

No 'Compress' devices detected
==============================

No 'Misc (rawdev)' devices detected
===================================

No 'Regex' devices detected
===========================

```

![QQ截图20210315140539](https://user-images.githubusercontent.com/22814611/111110488-987fcb80-8597-11eb-9e10-4550fcd40ed8.png)

I found some closed issues mentioned it before but mostly because of incompatible NICs. Did it do something wrong?

**Comment by tbarbette** [comment]
What is the output of sudo ~/fastclick/fastclick-master/bin/click --dpdk -c 0xf -n 4 -- ./test.click ?

**Comment by GrehXscape** [comment]
> What is the output of sudo ~/fastclick/fastclick-master/bin/click --dpdk -c 0xf -n 4 -- ./test.click ?

```
EAL: Detected 128 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Detected static linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: No legacy callbacks, legacy socket not created
./test.click:1: While configuring ‘FromDPDKDevice@1 :: FromDPDKDevice’:
  0: Unknown or invalid PORT
./test.click:1: While configuring ‘ToDPDKDevice@3 :: ToDPDKDevice’:
  1 : Unknown or invalid PORT
Router could not be initialized!

```

**Comment by tbarbette** [comment]
Somehow Click didn't build against the drivers. What was your build command line? And you installed DPDK using meson/ninja, right?

**Comment by GrehXscape** [comment]
> Somehow Click didn't build against the drivers. What was your build command line? And you installed DPDK using meson/ninja, right?

Yes, I build dpdk-20.11 with meson/ninja since the dpdk-setup.sh has been removed. And I build fastclick with
```
./configure --enable-dpdk --enable-intel-cpu --verbose --enable-select=poll CFLAGS="-O3" CXXFLAGS="-std=c++11 -O3"  --disable-dynamic-linking --enable-poll --enable-bound-port-transfer --enable-local --enable-flow --disable-task-stats --enable-cpu-load
make
```
which is the command line in README with ''disable-cpu-load" replaced by "enable-cpu-load", because I want to try out the RSS++.

**Comment by tbarbette** [comment]
I think it comes from "EAL: Detected static linkage of DPDK". I don't have that. Any particular arguments you gave to meson? A system-wide flag?

**Comment by tbarbette** [comment]
Can you launch also once with  --dpdk -v --log-level=9 -- and show the output?

**Comment by GrehXscape** [comment]
I build dpdk with
```
meson -Dexamples=all 
cd build
ninja
sudo ninja install
```
And with `sudo fastclick/fastclick-master/bin/click --dpdk -v --log-level=9 --` it shows

```
EAL: Detected 128 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: RTE Version: 'DPDK 20.11.1'
EAL: Detected static linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: No legacy callbacks, legacy socket not created
```
And then it stuck. I'll try to recompile the dpdk.
![QQ截图20210315194927](https://user-images.githubusercontent.com/22814611/111149227-946ba200-85c7-11eb-95bf-8f263861f621.png)

**Comment by tbarbette** [comment]
Ok this is due to the 20.11 LTS package. I can reproduce with that. You can use the git version and checkout the v20.11 tag meanwhile if you wish, it will work.

**Comment by GrehXscape** [comment]
> Ok this is due to the 20.11 LTS package. I can reproduce with that. You can use the git version and checkout the v20.11 tag meanwhile if you wish, it will work.

OK, I'll try to switch to DPDK 20.08 or other version first. Sorry for all this trouble I caused.

**Comment by GrehXscape** [comment]
I cloned the github version of dpdk and checkout the v20.11 tag, but still the same.
![QQ截图20210315224147](https://user-images.githubusercontent.com/22814611/111171210-ace7b680-85df-11eb-8fe4-c402b3e84264.png)
![QQ截图20210315224226](https://user-images.githubusercontent.com/22814611/111171277-bd982c80-85df-11eb-8efa-845282dd26c9.png)

**Comment by tbarbette** [comment]
And with the 20.11 you did bind the interface again?

**Comment by GrehXscape** [comment]
> And with the 20.11 you did bind the interface again?

Yes I did.
![QQ截图20210316092818](https://user-images.githubusercontent.com/22814611/111242365-fbc23a00-8639-11eb-8db7-fd011e38b73a.png)

**Comment by GrehXscape** [comment]
This is partially solved. I moved to another platform with Ubuntu 16.04, DPDK 20.08 (built with dpdk-setup.sh), same 82599 NIC and on-going network packet streams coming from a router in our campus. It can run fine with the following configuration and command line.
`FromDPDKDevice(0) -> CheckIPHeader(OFFSET 14) -> Print -> Discard`
`sudo ~/fastclick/fastclick/bin/click --dpdk -c 0xf -n 4 -- ./test.click`
The differences between the non-working platform and working platform are :
1. The non-working platform is a DUT, so it has no packets coming into the NIC right now (but already connected through wire with another server). The working one has (uncontrollable streams).
2. Running different OS
3. Build with different version of DPDK
I'll try to find out why this happen.

**Comment by GrehXscape** [comment]
> This is partially solved. I moved to another platform with Ubuntu 16.04, DPDK 20.08 (built with dpdk-setup.sh), same 82599 NIC and on-going network packet streams coming from a router in our campus. It can run fine with the following configuration and command line.
> `FromDPDKDevice(0) -> CheckIPHeader(OFFSET 14) -> Print -> Discard`
> `sudo ~/fastclick/fastclick/bin/click --dpdk -c 0xf -n 4 -- ./test.click`
> The differences between the non-working platform and working platform are :
> 
> 1. The non-working platform is a DUT, so it has no packets coming into the NIC right now (but already connected through wire with another server). The working one has (uncontrollable streams).
> 2. Running different OS
> 3. Build with different version of DPDK
>    I'll try to find out why this happen.

I tested it on the former platform with DPDK 20.08. The error remains when DPDK was compiled with meson/ninja but disappears when compiled with make.

**Comment by tbarbette** [comment]
It's not related to the fact packet flows, as in your first setup the NIC cannot be found... I still have to dig more into this.

**Comment by tbarbette** [comment]
Sorry, I took a bit of time but the linking problem is fixed :)

For the error in the original post, it is a false positive that comes from Click itself, I won't fix it for now.

**Comment by tbarbette** [comment]
Note that if you compile without --disable-dynamic-linking, you must load drivers manually with the "-d" DPDK arguments. But just compile with --disable-dynamic-linking, for the best performance it's better anyway...
