### ISSUE TITLE
Measuring throughput with FastClick

### ISSUE THREAD

**Issue by p4pe** [tbarbette/fastclick#329]
Hello, I started experimenting with FastClick, and I want to measure the throughput (on the sink) in the following topology:
![emula](https://user-images.githubusercontent.com/35313995/112847322-a3665000-90af-11eb-87ee-e123abb91473.png)

All the nodes have DPDK version 19.11.7 (LTS) installed (using the dpdk-setup.sh script).

DPDK attached interface on the Source server:
![dpdk-source](https://user-images.githubusercontent.com/35313995/112848114-63ec3380-90b0-11eb-8887-9f1a5c4f4429.png)

DPDK attached interfaces on  VNF server:
![dpdk-vnf](https://user-images.githubusercontent.com/35313995/112848540-da893100-90b0-11eb-8696-d9c93b1d052b.png)

DPDK attached interface on the Sink server:
![dpdk-source](https://user-images.githubusercontent.com/35313995/112848114-63ec3380-90b0-11eb-8887-9f1a5c4f4429.png)

FastClick Configuration

Source Server | Traffic generator
```
InfiniteSource(LENGTH 1500, LIMIT 1000000000, STOP true)
-> UDPIPEncap(192.168.1.1, 50, 192.168.1.13, 100, 1)
-> EtherEncap(0x800,3c:fd:fe:04:ad:40, 3c:fd:fe:05:9b:80)
-> c::Counter
-> ToDPDKDevice(0000:06:00.1)

Script(wait 1, print c.rate, loop)
```
Running the configuration: ``` ./click --dpdk -c 0xf -n -4 -- generator.click```
![traffic](https://user-images.githubusercontent.com/35313995/112849757-08bb4080-90b2-11eb-9456-722d74b25c71.png)

VNF Server |  FastClick configuration script

```
FromDPDKDevice(0000:06:00.0, PROMISC true) -> Print() -> c::AverageCounter()->ToDPDKDevice(0000:06:00.1)
  Script(wait 1, print c.rate, loop)
```

Unfortunately, I did not capture any packet in the VNF server. Where is my mistake?

Moreover, Ιs there any alternative tool like tcpdump for dpdk devices??

**Comment by tbarbette** [comment]
> Moreover, Ιs there any alternative tool like tcpdump for dpdk devices??

Nope, DPDK gives the NIC to the application. But in FastClick you have IPPrint().

Maybe start by naming your FromDPDKDevice in the VNF server "fd0" then add  DriverManager(wait, read fd0.xstats); You'll have the extended devices statistics that will show you if the packets were at least seen.

**Comment by tbarbette** [comment]
Is this solved?

**Comment by p4pe** [comment]
Yes !
