### ISSUE TITLE
Build Error on Ubuntu 20.04

### ISSUE THREAD

**Issue by Qcloud1223** [tbarbette/fastclick#333]
Hello, I've ran into some problems when trying to follow the build instructions in README:
```
/usr/bin/ld: /tmp/packetmill-28a4bd.o: in function `main':
packetmill.cc:(.text+0xfe4): undefined reference to `optimizeIR(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:196: packetmill] Error 1
make[1]: Leaving directory '/home/dyh/fastclick/userlevel'
make: *** [Makefile:58: userlevel] Error 2
```

I'm on Ubuntu 20.04 with Intel 82599es NIC and Xeon Gold 6248R CPU.

Thank you in advance!

**Comment by tbarbette** [comment]
Ah I probably introduce that regression with the related packetmill merge. I'll look at it now.

**Comment by tbarbette** [comment]
Note that I also overwrite FastClick's instructions with PacketMill's instructions. If you just want FastClick, I'd suggest to use the command line now in the README ;)

**Comment by Qcloud1223** [comment]
Thanks a lot for your quick response! Now it builds without problem :)
