### ISSUE TITLE
Create Element

### ISSUE THREAD

**Issue by ali64mohammad** [tbarbette/fastclick#338]
Hi
I used Click before and wrote some Elements as a package according to this document in the click:
_There are two ways to add an element class to Click: in the main Click collection, or in a package. We recommend that you use packages for nontrivial collections of elements. It has several advantages -- for example, it will keep your code separate from the main Click code. Check out the sample package in 'etc/samplepackage'._

so I use the sample package and wrote my elements.

but in fast click documents I don't see mentioned to package elements,
is fast click support them?
can I use my element package from click in fast click too? 
thanks

**Comment by tbarbette** [comment]
Normally it works, yes. If you have a specific issue feel free to post it here.

**Comment by ali64mohammad** [comment]
Thanks alot
