### ISSUE TITLE
port 0 Rx queue allocation failed: Cannot allocate memory

### ISSUE THREAD

**Issue by cxxuser** [tbarbette/fastclick#357]
Hello，I have faced a issue many days. My command and codes are shown below:

$ sudo ./click --dpdk -l 0-35 -n 6 -w 0000:18:00.1 -v -- GEN_LENGTH=64 TXM
EAL: Detected 96 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: RTE Version: 'DPDK 20.05.0-rc4'
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: Probe PCI driver: net_mlx5 (15b3:a2d2) device: 0000:18:00.1 (socket 0)
net_mlx5: tunnel offloading disabled due to old OFED/rdma-core version
net_mlx5: MPLS over GRE/UDP tunnel offloading disabled due to old OFED/rdma-core version or firmware configuration
net_mlx5: DV flow is not supported
EAL: No legacy callbacks, legacy socket not created
TXM:8: While configuring ‘d :: DPDKInfo’:
  warning: The number of MBUFs is (4196) not a power of 2 minus one. This will decrease performances.
gen0/fd: 20 threads will be used to push packets downstream. 20 queues will be used meaning that each queue will be shared by 1 threads
gen0/fd: using queues from 0 to 19
gen0/fd: Queue 0 handled by th 4
gen0/fd: Queue 1 handled by th 5
gen0/fd: Queue 2 handled by th 6
gen0/fd: Queue 3 handled by th 7
gen0/fd: Queue 4 handled by th 8
gen0/fd: Queue 5 handled by th 9
gen0/fd: Queue 6 handled by th 10
gen0/fd: Queue 7 handled by th 11
gen0/fd: Queue 8 handled by th 12
gen0/fd: Queue 9 handled by th 13
gen0/fd: Queue 10 handled by th 14
gen0/fd: Queue 11 handled by th 15
gen0/fd: Queue 12 handled by th 16
gen0/fd: Queue 13 handled by th 17
gen0/fd: Queue 14 handled by th 18
gen0/fd: Queue 15 handled by th 19
gen0/fd: Queue 16 handled by th 20
gen0/fd: Queue 17 handled by th 21
gen0/fd: Queue 18 handled by th 22
gen0/fd: Queue 19 handled by th 23
Initializing DPDK
net_mlx5: port 0 empty mbuf pool
net_mlx5: port 0 Rx queue allocation failed: Cannot allocate memory
TXM:43: While initializing ‘gen0/tdOUT :: ToDPDKDevice’:
  Cannot start DPDK port 0: error -12
Router could not be initialized!

**My codes are very similar to https://github.com/tbarbette/npf/blob/master/modules/fastclick-udpgen-latency-single.npf.**
I have seen a solution in stackoverflow：

_The issue is related to the TX inlining feature of the MLX5 driver, which is only enabled when the number of queues is >=8. TX inlining uses DMA to send the packet directly to the host memory buffer.

With TX inlining, there are some checks that fail in the underlying verbs library (which is called from DPDK during QP Creation) if a large number of descriptors is used. So a workaround is to use fewer descriptors._

**so，I modified the code ：
tdOUT::ToDPDKDevice($port, BLOCKING $GEN_BLOCKING); --> tdOUT::ToDPDKDevice($port, BLOCKING $GEN_BLOCKING, NDESC 65);**

However, I get the screen output below：
EAL: Detected 96 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: RTE Version: 'DPDK 20.05.0-rc4'
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: Probe PCI driver: net_mlx5 (15b3:a2d2) device: 0000:18:00.1 (socket 0)
net_mlx5: tunnel offloading disabled due to old OFED/rdma-core version
net_mlx5: MPLS over GRE/UDP tunnel offloading disabled due to old OFED/rdma-core version or firmware configuration
net_mlx5: DV flow is not supported
EAL: No legacy callbacks, legacy socket not created
TXM:8: While configuring ‘d :: DPDKInfo’:
  warning: The number of MBUFs is (4196) not a power of 2 minus one. This will decrease performances.
gen0/fd: 20 threads will be used to push packets downstream. 20 queues will be used meaning that each queue will be shared by 1 threads
gen0/fd: using queues from 0 to 19
gen0/fd: Queue 0 handled by th 4
gen0/fd: Queue 1 handled by th 5
gen0/fd: Queue 2 handled by th 6
gen0/fd: Queue 3 handled by th 7
gen0/fd: Queue 4 handled by th 8
gen0/fd: Queue 5 handled by th 9
gen0/fd: Queue 6 handled by th 10
gen0/fd: Queue 7 handled by th 11
gen0/fd: Queue 8 handled by th 12
gen0/fd: Queue 9 handled by th 13
gen0/fd: Queue 10 handled by th 14
gen0/fd: Queue 11 handled by th 15
gen0/fd: Queue 12 handled by th 16
gen0/fd: Queue 13 handled by th 17
gen0/fd: Queue 14 handled by th 18
gen0/fd: Queue 15 handled by th 19
gen0/fd: Queue 16 handled by th 20
gen0/fd: Queue 17 handled by th 21
gen0/fd: Queue 18 handled by th 22
gen0/fd: Queue 19 handled by th 23
Initializing DPDK
net_mlx5: port 0 increased number of descriptors in Tx queue 0 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 1 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 2 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 3 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 4 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 5 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 6 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 7 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 8 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 9 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 10 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 11 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 12 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 13 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 14 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 15 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 16 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 17 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 18 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 19 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 20 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 21 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 22 to the next power of two (128)
net_mlx5: port 0 increased number of descriptors in Tx queue 23 to the next power of two (128)
net_mlx5: port 0 empty mbuf pool
net_mlx5: port 0 Rx queue allocation failed: Cannot allocate memory
TXM:43: While initializing ‘gen0/tdOUT :: ToDPDKDevice’:
  Cannot start DPDK port 0: error -12
Router could not be initialized!

I'm still facing the same problem,
 **"net_mlx5: port 0 empty mbuf pool 
  net_mlx5: port 0 Rx queue allocation failed: Cannot allocate memory
  TXM:43: While initializing ‘gen0/tdOUT :: ToDPDKDevice’: "**

What should I do to solve the problem?

regard

**Comment by aliireza** [comment]
Hi,

The error is saying that DPDK cannot allocate memory, so I think you need to reserve some hugepages. 

There are two ways to do it:
(i) Reserve them at boot-time via GRUB, see here: https://github.com/aliireza/ddio-bench/blob/master/TESTBED.md#other-commandlines
(ii) Reserve them at run-time, see here: https://doc.dpdk.org/guides/tools/hugepages.html

Note that the second method only works for 2-MB hugepages, not 1-GB hugepages. 

There is an alternative way to run your code without hugepages. You have to enable IOMMU and then run click with `--iova-mode=va --no-huge -m 1024`, but it will be less performant due to TLB/IOMMU performance penalties.

```bash
sudo ./click --dpdk -l 0-35 -n 6 -w 0000:18:00.1 -v --iova-mode=va --no-huge -m 1024 -- GEN_LENGTH=64 TXM
```

**Comment by cxxuser** [comment]
> Hi,
> 
> The error is saying that DPDK cannot allocate memory, so I think you need to reserve some hugepages.
> 
> There are two ways to do it: (i) Reserve them at boot-time via GRUB, see here: https://github.com/aliireza/ddio-bench/blob/master/TESTBED.md#other-commandlines (ii) Reserve them at run-time, see here: https://doc.dpdk.org/guides/tools/hugepages.html
> 
> Note that the second method only works for 2-MB hugepages, not 1-GB hugepages.
> 
> There is an alternative way to run your code without hugepages. You have to enable IOMMU and then run click with `--iova-mode=va --no-huge -m 1024`, but it will be less performant due to TLB/IOMMU performance penalties.
> 
> ```shell
> sudo ./click --dpdk -l 0-35 -n 6 -w 0000:18:00.1 -v --iova-mode=va --no-huge -m 1024 -- GEN_LENGTH=64 TXM
> ```

Thanks for replying，
I have not completely understand what is “to reserve some hugepages” ，I have run this command：

**echo 1024 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages**

Which means that I have reserved the hugepages？

regard

**Comment by cxxuser** [comment]
> Hi,
> 
> The error is saying that DPDK cannot allocate memory, so I think you need to reserve some hugepages.
> 
> There are two ways to do it: (i) Reserve them at boot-time via GRUB, see here: https://github.com/aliireza/ddio-bench/blob/master/TESTBED.md#other-commandlines (ii) Reserve them at run-time, see here: https://doc.dpdk.org/guides/tools/hugepages.html
> 
> Note that the second method only works for 2-MB hugepages, not 1-GB hugepages.
> 
> There is an alternative way to run your code without hugepages. You have to enable IOMMU and then run click with `--iova-mode=va --no-huge -m 1024`, but it will be less performant due to TLB/IOMMU performance penalties.
> 
> ```shell
> sudo ./click --dpdk -l 0-35 -n 6 -w 0000:18:00.1 -v --iova-mode=va --no-huge -m 1024 -- GEN_LENGTH=64 TXM
> ```

Thanks for your reply，

I haven't completely understood what's the meanings of "reserve some hugepages".
I have run the command "**echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages**"

Which means I have reserved some hugepages?


"dpdk-hugepages.py" and "cat /proc/meminfo" outputs:
**And these are "dpdk-hugepages.py -s" screen outputs:**
Node Pages Size Total
0    1     1Gb    1Gb
0    1024  2Mb    2Gb
1    1024  2Mb    2Gb

Hugepages mounted on /dev/hugepages /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb

these are "cat /proc/meminfo" outputs:
MemTotal:       131485532 kB
MemFree:        72428400 kB
MemAvailable:   84790696 kB
Buffers:            2256 kB
Cached:         16482264 kB
SwapCached:            0 kB
Active:         36587612 kB
Inactive:       11816568 kB
Active(anon):   32771328 kB
Inactive(anon):  4075908 kB
Active(file):    3816284 kB
Inactive(file):  7740660 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       4194300 kB
SwapFree:        4194300 kB
Dirty:               712 kB
Writeback:             0 kB
AnonPages:      31920472 kB
Mapped:          1055216 kB
Shmem:           4927468 kB
Slab:            2100912 kB
SReclaimable:    1431364 kB
SUnreclaim:       669548 kB
KernelStack:       71248 kB
PageTables:       312512 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    67315624 kB
Committed_AS:   61120212 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      744932 kB
VmallocChunk:   34291746812 kB
Percpu:           227968 kB
HardwareCorrupted:     0 kB
AnonHugePages:   1865728 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:    2048
HugePages_Free:     2041
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      438236 kB
DirectMap2M:    11794432 kB
DirectMap1G:    123731968 kB


From these outputs can prove that I have reserved the hugepages? 

regard!

**Comment by cxxuser** [comment]
> Hi,
> 
> The error is saying that DPDK cannot allocate memory, so I think you need to reserve some hugepages.
> 
> There are two ways to do it: (i) Reserve them at boot-time via GRUB, see here: https://github.com/aliireza/ddio-bench/blob/master/TESTBED.md#other-commandlines (ii) Reserve them at run-time, see here: https://doc.dpdk.org/guides/tools/hugepages.html
> 
> Note that the second method only works for 2-MB hugepages, not 1-GB hugepages.
> 
> There is an alternative way to run your code without hugepages. You have to enable IOMMU and then run click with `--iova-mode=va --no-huge -m 1024`, but it will be less performant due to TLB/IOMMU performance penalties.
> 
> ```shell
> sudo ./click --dpdk -l 0-35 -n 6 -w 0000:18:00.1 -v --iova-mode=va --no-huge -m 1024 -- GEN_LENGTH=64 TXM
> ```

Hi, Thanks for your reply,

I haven't completely understood what's the meanings of "reserve some hugepages".
I have run the command "echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages"

Which means I have reserved some hugepages?

"dpdk-hugepages.py" and "cat /proc/meminfo" outputs:
And these are "dpdk-hugepages.py -s" screen outputs:
Node Pages Size Total
0 1 1Gb 1Gb
0 1024 2Mb 2Gb
1 1024 2Mb 2Gb

Hugepages mounted on /dev/hugepages /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb /dev/hugepages_1gb /dev/hugepages_2mb

these are "cat /proc/meminfo" outputs:
MemTotal: 131485532 kB
MemFree: 72428400 kB
MemAvailable: 84790696 kB
Buffers: 2256 kB
Cached: 16482264 kB
SwapCached: 0 kB
Active: 36587612 kB
Inactive: 11816568 kB
Active(anon): 32771328 kB
Inactive(anon): 4075908 kB
Active(file): 3816284 kB
Inactive(file): 7740660 kB
Unevictable: 0 kB
Mlocked: 0 kB
SwapTotal: 4194300 kB
SwapFree: 4194300 kB
Dirty: 712 kB
Writeback: 0 kB
AnonPages: 31920472 kB
Mapped: 1055216 kB
Shmem: 4927468 kB
Slab: 2100912 kB
SReclaimable: 1431364 kB
SUnreclaim: 669548 kB
KernelStack: 71248 kB
PageTables: 312512 kB
NFS_Unstable: 0 kB
Bounce: 0 kB
WritebackTmp: 0 kB
CommitLimit: 67315624 kB
Committed_AS: 61120212 kB
VmallocTotal: 34359738367 kB
VmallocUsed: 744932 kB
VmallocChunk: 34291746812 kB
Percpu: 227968 kB
HardwareCorrupted: 0 kB
AnonHugePages: 1865728 kB
CmaTotal: 0 kB
CmaFree: 0 kB
HugePages_Total: 2048
HugePages_Free: 2041
HugePages_Rsvd: 0
HugePages_Surp: 0
Hugepagesize: 2048 kB
DirectMap4k: 438236 kB
DirectMap2M: 11794432 kB
DirectMap1G: 123731968 kB

These outputs can prove that I have reserved the hugepages?

regard!

**Comment by aliireza** [comment]
Hi,

You cannot always allocate hugepages at runtime (specifically 1-GB hugepages), so you have to reserve them at boot time, where a contiguous memory will be put aside to be used by the applications, and it will not be available to the operating system.

Yes! The output shows that you have enough hugepages. 

Maybe wait for others to reply.

Cheers,
Alireza

**Comment by tbarbette** [comment]
I thought like Alireza that it was a hugepage issue, but it's apparently not.

The problem might be that your system has multiple NUMA nodes, and the configuration is assuming the use of the first numa node only, so it allocates 4096 buffers to the second NUMA node. That's not enough to create your queues.

You might want to set the number of buffers per NUMA node in DPDKInfo according to the device/configuration.   You can use for instance `DPDKInfo(NB_SOCKET_MBUF 65535, NB_SOCKET_MBUF 65535);`

**Comment by cxxuser** [comment]
> I thought like Alireza that it was a hugepage issue, but it's apparently not.
> 
> The problem might be that your system has multiple NUMA nodes, and the configuration is assuming the use of the first numa node only, so it allocates 4096 buffers to the second NUMA node. That's not enough to create your queues.
> 
> You might want to set the number of buffers per NUMA node in DPDKInfo according to the device/configuration. You can use for instance `DPDKInfo(NB_SOCKET_MBUF 65535, NB_SOCKET_MBUF 65535);`

Thanks for your reply,

I followed your tutorials: https://github.com/tbarbette/fastclick/wiki/DPDKInfo and https://github.com/tbarbette/npf/blob/master/modules/fastclick-udpgen-latency-single.npf

Using NBBUF=EXPAND( $(( (($LIMIT + ($GEN_BURST * 2) ) * $GEN_THREADS ) + 8192 )) ) and d :: DPDKInfo($NBBUF) to configure the number of buffers.

However, which may be too large to allocate (the value of NBBUF = 4009216) ,so I modified the value of NBBUF to 65535.
But, which doesn't work out, I still get the same screen outputs below:
Initializing DPDK
Loading gen0/gen1/replay with 1 inputs.
Loading gen0/gen2/replay with 1 inputs.
Loading gen0/gen3/replay with 1 inputs.
Loading gen0/gen0/replay with 1 inputs.
**No more DPDK buffer available ! Try using DPDKInfo to allocate more.
gen0/gen1/EnsureDPDKBuffer@3: No more DPDK buffer! Dropping packet.
No more DPDK buffer! Dropping packet 0x7f8f700019b0!
gen0/gen1/replay : Successfully loaded 14392 packets. Input 0 dried out.
No more DPDK buffer available ! Try using DPDKInfo to allocate more.
No more DPDK buffer available ! Try using DPDKInfo to allocate more.**

When I going on to decrease the value of NBBUF to 4096, the screen outputs has changed to the title of the issues:
**Initializing DPDK
net_mlx5: port 0 empty mbuf pool
net_mlx5: port 0 Rx queue allocation failed: Cannot allocate memory
TXM:43: While initializing ‘gen0/tdOUT :: ToDPDKDevice’:
Cannot start DPDK port 0: error -12
Router could not be initialized!**

**My system is NUMA machine of two nodes，and DPDK detect that：
"EAL: Detected 96 lcore(s)
 EAL: Detected 2 NUMA nodes"

I wonder that using d :: DPDKInfo($NBBUF) only allocate buffers to one port?

When the value of NBBUF is large,eg 65535, the error reports is not 
"net_mlx5: port 0 empty mbuf pool
net_mlx5: port 0 Rx queue allocation failed: Cannot allocate memory"
but 
"No more DPDK buffer available ! Try using DPDKInfo to allocate more.
gen0/gen0/EnsureDPDKBuffer@3: No more DPDK buffer! Dropping packet.
No more DPDK buffer! Dropping packet 0x29761c0!
gen0/gen0/replay : Successfully loaded 15954 packets. Input 0 dried out.
No more DPDK buffer available ! Try using DPDKInfo to allocate more.
No more DPDK buffer
No more DPDK buffer available ! Try using DPDKInfo to allocate more.
Aborted"**

If I only allocated buffer for only one port, why the error reports is not "net_mlx5: port 0 Rx queue allocation failed: Cannot allocate memory",when the value of NBBUF is large.

regard

**Comment by cxxuser** [comment]
> DPDKInfo(NB_SOCKET_MBUF 65535, NB_SOCKET_MBUF 65535);

Hi, Tom!

I have modified the  "d :: DPDKInfo( 4009216 ); "  to  "d :: DPDKInfo(NB_SOCKET_MBUF 4009216, NB_SOCKET_MBUF 4009216);"

However, I get the similiar error reports:
  **warning: The number of MBUFs for socket 0 (4009216) is not a power of 2 minus one. This will decrease performances.
  warning: The number of MBUFs for socket 1 (4009216) is not a power of 2 minus one. This will decrease performances.
Initializing DPDK
TXM:84: While initializing ‘tdOUT :: ToDPDKDevice’:
  Could not allocate packet MBuf pools 0 with 4009216 buffers : error 105 (No buffer space available)
Router could not be initialized!**

So, I think maybe that I set the wrong value of NB_MBUF. But, if I decreased the value of NB_MBUF，I would get the below error reports：
**Initializing DPDK
Loading gen0/gen1/replay with 1 inputs.
Loading gen0/gen2/replay with 1 inputs.
Loading gen0/gen3/replay with 1 inputs.
Loading gen0/gen0/replay with 1 inputs.
No more DPDK buffer available ! Try using DPDKInfo to allocate more.
gen0/gen0/EnsureDPDKBuffer@3: No more DPDK buffer! Dropping packet.
No more DPDK buffer! Dropping packet 0x25a71c0!
gen0/gen0/replay : Successfully loaded 16982 packets. Input 0 dried out.
No more DPDK buffer available ! Try using DPDKInfo to allocate more.
No more DPDK buffer
Aborted**

I realized I'm in a dilemma, no matter how I set the value of NB_MBUF, I always faces a error report.

If I set a large value , it will reports "error 105 (No buffer space available)"; and if I set a smaller one,eg 65535, it will reports"No more DPDK buffer available ! Try using DPDKInfo to allocate more."

I really don't know why the dilemma will happen and if I have some misunderstandings about the codes. Looking forward to your replys.

regard

**Comment by tbarbette** [comment]
Hi!

It's a simple memory error actually, the number of buffer you asked for is too large for the number of hugepages you allocated. Roughly one buffer is 2176B, so if you ask for 4M buffers per socket you need at least 18G of memory in hugepages. But you have 2048*2M = 4G, not near enough.

The problem if you ask for less buffers is that you can't preload all packets, eventually one memory/buffer allocation fails. So you can either replace ReplayUnqueue by Unqueue which will not preload packets, or limit the number of preloaded packets with $LIMIT. Or are you using NPF? in which case you can use fastclick-play-single-mt instead and have the udpgen tag. But without preloading you can't reach 100G. play-single-mt have some crazy options to go faster that we can discuss though.

Cheers,
Tom
