### ISSUE TITLE
storeing data in packet

### ISSUE THREAD

**Issue by ali64mohammad6464** [tbarbette/fastclick#360]
Hi
i want to add some data to packets for example parse new protocol or some flag that i need in next elements and store parsed information in packet.
where do you suggest to store custom data for packet and how?
The solution must be such that it is compatible with click structure for example if packet reassembled or fragmented, the information will not be lost.
thanks.

**Comment by pallas** [comment]
You add a CB annotation and make sure the space is large enough. 

~Derrick • iPhone

**Comment by tbarbette** [comment]
@pallas's suggestion seems to be the best. Look at packet_anno.hh, or for usage of PAINT_ANNO and SET_PAINT_ANNO.
