### ISSUE TITLE
How to use replayUnqueue or MultiReplayUnqueue to limit the tx rate?

### ISSUE THREAD

**Issue by Emikoer** [tbarbette/fastclick#367]
I use the example under conf/pktgen/pktgen-l2.click to generate packets, but I don't know how to use replayUnqueue or MultiReplayUnqueue to limit the tx rate. 
`FastUDPSouce(RATE 0,LIMIT $N, LENGTH $L, SRCETH $mymac,SRCIP $myip,SPORT 8000, DSTETH $dmac, DSTIP $dstip, DPORT 8000)`
`-> MarkMACHeader`
`-> EnsureDPDKBuffer`
`-> replay :: MultiReplayUnqueue(STOP -1, ACTIVE false, QUICK_CLONE 1)`
`-> ic0 :: AverageCounter()`
`-> td :: ToDPDKDevice(0000:04:00.1, BLOCKING $blocking, VERBOSE $verbose)`

**Comment by tbarbette** [comment]
Another way to go would be to modify ReplayUnqueue to use some kind of fake rate instead of the packet timestamp, around https://github.com/tbarbette/fastclick/blob/f99c521dd46341394a1343dccc043f3625360435/elements/analysis/replay.cc#L328

**Comment by Emikoer** [comment]
Thanks for your answer! I tried to use BandwidthRatedUnqueue and it succeed.
