### ISSUE TITLE
middleclick configuration 

### ISSUE THREAD

**Issue by hedj17** [tbarbette/fastclick#369]
Hi Tom
I have used the configure command in README.middleclick.md
`./configure --enable-multithread --disable-linuxmodule --enable-intel-cpu --enable-user-multithread --verbose CFLAGS="-g -O3" CXXFLAGS="-g -std=gnu++11 -O3" --disable-dynamic-linking --enable-poll --enable-bound-port-transfer --enable-dpdk --enable-batch --with-netmap=no --enable-zerocopy --disable-dpdk-pool --disable-dpdk-packet --enable-user-timestamp --enable-flow --enable-ctx`

However, when I run command
`bin/click --dpdk -- conf/middleclick/firewall.click`
gives me
EAL: Detected 48 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Detected static linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available 1048576 kB hugepages reported
EAL: Probe PCI driver: mlx5_pci (15b3:1017) device: 0000:3e:00.0 (socket 0)
TELEMETRY: No legacy callbacks, legacy socket not created
conf/middleclick/firewall.click:15: unknown element class ‘FlowUnstrip’
conf/middleclick/firewall.click:24: undeclared element ‘CTXDispatcher’
conf/middleclick/firewall.click:32: undeclared element ‘CTXDispatcher’
conf/middleclick/firewall.click:50: unknown element class ‘CTXDispatcher’
conf/middleclick/firewall.click:55: unknown element class ‘FlowClassifier’
conf/middleclick/firewall.click:55: undeclared element ‘FlowStrip’

What causes this problem?  when I run other examples,  it does not produce any error.  Does middleclick need any dependencies other than dpdk?

There are very few tutorials on middleclick and could you supply some?

**Comment by tbarbette** [comment]
The elements did not compile for some reason. I'll check that !
