### ISSUE TITLE
click-devirtualize support?

### ISSUE THREAD

**Issue by rstory** [tbarbette/fastclick#37]
Hello. I'm trying to run click-devirtualize on a fairly basic config. After some tweaks to deal with DPDK, I can get the devirtualized code to compile without errors, but then I end up with a slew of undefined references:

$ click-devirtualize -d -u router-2if-shaped-sm16 > router-2if-shaped-sm16.dv 
/usr/local/bin/click-buildtool makepackage -C /tmp/clicktmp25355/ -t userlevel  -w -fno-access-control -I/usr/local/include/dpdk  clickdv_8hmRp6kM7fFhsMbe7LtiMb clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.cc 1>&2
+ make clickdv_8hmRp6kM7fFhsMbe7LtiMb.uo
make -R CLICK_PACKAGE_MAKING=userlevel clickdv_8hmRp6kM7fFhsMbe7LtiMb.uo
make[1]: Entering directory '/tmp/clicktmp25355'
  CXX clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.cc
g++ -g -std=gnu++11 -O3 -Wno-pmf-conversions -fPIC  -o clickdv_8hmRp6kM7fFhsMbe7LtiMb.uo clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.u.o     
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.u.o: In function `Discard_a_aDiscard_a24::Discard_a_aDiscard_a24()':
/tmp/clicktmp25355/clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.hh:161: undefined reference to `Discard::Discard()'
clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.u.o: In function `SetTimestamp_a_aSetTimestamp_a26::SetTimestamp_a_aSetTimestamp_a26()':
/tmp/clicktmp25355/clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.hh:172: undefined reference to `SetTimestamp::SetTimestamp()'
clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.u.o: In function `FromDPDKDevice_a_ain0::FromDPDKDevice_a_ain0()':
/tmp/clicktmp25355/clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.hh:11: undefined reference to `FromDPDKDevice::FromDPDKDevice()'
clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.u.o: In function `Classifier_a_ac0::Classifier_a_ac0()':
/tmp/clicktmp25355/clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.hh:22: undefined reference to `Classifier::Classifier()'
clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.u.o: In function `ToDPDKDevice_a_aout0::ToDPDKDevice_a_aout0()':
/tmp/clicktmp25355/clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.hh:34: undefined reference to `ToDPDKDevice::ToDPDKDevice()'
clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.u.o: In function `ARPResponder_a_aresponder0::ARPResponder_a_aresponder0()':
/tmp/clicktmp25355/clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.hh:45: undefined reference to `ARPResponder::ARPResponder()'
clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.u.o: In function `ARPQuerier_a_aarp0::ARPQuerier_a_aarp0()':
/tmp/clicktmp25355/clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.hh:60: undefined reference to `ARPQuerier::ARPQuerier()'
...
clickdv_8hmRp6kM7fFhsMbe7LtiMb.u.u.o:(.data.rel.ro._ZTV32SetTimestamp_a_aSetTimestamp_a26[_ZTV32SetTimestamp_a_aSetTimestamp_a26]+0xf0): undefined reference to `Element::llrpc(unsigned int, void*)'
collect2: error: ld returned 1 exit status
/usr/local/share/click/pkg-userlevel.mk:84: recipe for target 'clickdv_8hmRp6kM7fFhsMbe7LtiMb.uo' failed
make[1]: *** [clickdv_8hmRp6kM7fFhsMbe7LtiMb.uo] Error 1
make[1]: Leaving directory '/tmp/clicktmp25355'

Any suggestions on how to get a loadable module for userspace greatly appreciated.

**Comment by tbarbette** [comment]
Hi,

Batching is certainly not supported by click-devirtualize, but I did not specifically looked at DPDK support (either mainline DPDK or FastClick DPDK).

First, does the tool work without DPDK (removing specific DPDK elements and enable-dpdk)? If that doesn't work, you'd be better with asking the question on mainline Click (kohler/click). If so, does it break when you add --enable-dpdk, or when you add DPDK elements?

Devirtualize is probably more broken here than in mainline, you may start with pure mainline Click and then move to FastClick when it works.

Tom

**Comment by rstory** [comment]
When I take out dpdk support, I get the same result with fastclick as I get with mainline, which is system header conflicts when building. I've opened an issue there. (https://github.com/kohler/click/issues/348)

**Comment by rstory** [comment]
Changes (so far) for dpdk support in click-devirtualize, if anyone is interested: https://github.com/rstory/fastclick/tree/devirt-dpdk

**Comment by tbarbette** [comment]
Any advance on this? Is it working?

**Comment by rstory** [comment]
No progress. No response so far to upstream header conflict ticket.
