### ISSUE TITLE
compile error about context

### ISSUE THREAD

**Issue by hedj17** [tbarbette/fastclick#370]
Hi, Tom
At last week, I proposed the issue about middle click,  and you updated configure fie. Howeve, there are new issues during compile time and I haven't encountered this problem before.  Could you help me? 

In file included from ../elements/analysis/multireplay.hh:9:0,
                 from ../elements/analysis/multireplay.cc:21:
../elements/analysis/replay.hh: In member function ‘bool ReplayBase::load_packets()’:
../elements/analysis/replay.hh:155:37: error: ‘Element::batch_mode Element::in_batch_mode’ is protected within this context
             if (input(i).element()->in_batch_mode) {
                                     ^~~~~~~~~~~~~
In file included from ../include/click/router.hh:4:0,
                 from ../include/click/master.hh:4,
                 from ../include/click/batchelement.hh:9,
                 from ../elements/analysis/multireplay.hh:4,
                 from ../elements/analysis/multireplay.cc:21:
../include/click/element.hh:382:21: note: declared protected here
     enum batch_mode in_batch_mode;
                     ^~~~~~~~~~~~~
elements.mk:437: recipe for target 'multireplay.o' failed
make[1]: *** [multireplay.o] Error 1

**Comment by tbarbette** [comment]
Ah yes, sorry I got interrupted and forgot! Compilation is fixed, I'll fix the CI later.
