### ISSUE TITLE
--disable-test causes packetmill linker issue

### ISSUE THREAD

**Issue by Emilevillette** [tbarbette/fastclick#404]
Configuring Fastclick with `./configure --disable-test` followed by `sudo make install` on Debian 14 causes the building process to fail and produces the following output : 

```
  CXXLINK packetmill.cc
/usr/bin/ld: /tmp/ccRkDmPg.o: in function `parse(int, char**, click_args_t&)':
/home/vboxuser/fastclick/userlevel/args.hh:144: undefined reference to `Clp_NewParser'
/usr/bin/ld: /home/vboxuser/fastclick/userlevel/args.hh:145: undefined reference to `Clp_ProgramName'
/usr/bin/ld: /home/vboxuser/fastclick/userlevel/args.hh:148: undefined reference to `Clp_Next'
/usr/bin/ld: /tmp/ccRkDmPg.o: in function `parse(int, char**, click_args_t&)':
/home/vboxuser/fastclick/userlevel/packetmill.cc:21: undefined reference to `Clp_DeleteParser'
/usr/bin/ld: /home/vboxuser/fastclick/userlevel/packetmill.cc:21: undefined reference to `Clp_DeleteParser'
/usr/bin/ld: /home/vboxuser/fastclick/userlevel/packetmill.cc:21: undefined reference to `Clp_DeleteParser'
/usr/bin/ld: /tmp/ccRkDmPg.o: in function `parse(int, char**, click_args_t&)':
/home/vboxuser/fastclick/userlevel/args.hh:203: undefined reference to `Clp_OptionError'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:214: packetmill] Error 1
make[1]: Leaving directory '/home/vboxuser/fastclick/userlevel'
make: *** [Makefile:71: install-userlevel] Error 2
```

This seems to be related to clp being excluded from the building process, despite `clp.o` appearing in the trace

[trace.txt](https://github.com/user-attachments/files/17561185/trace.txt)

**Comment by tbarbette** [comment]
Did you "make clean" before? That looks more like some leftovers linker problem.

**Comment by Emilevillette** [comment]
Hello,

I wasn't sure anymore, so I reran it for good measure (`./configure --disable-test && sudo make clean && sudo make install -j 8`). It did produce the same error, trace :

[trace.txt](https://github.com/user-attachments/files/17594655/trace.txt)

After a bit of investigating, I found out using `grep -rni "clp.h" .`  that the only element that mentions `clp` is `elements/test/clptest.cc`, which was an indicator that somehow the `--disable-test` option could be linked to the issue.

Since it's the building process of Packetmill which is failing, I checked the difference in `userlevel/Makefile` when using `./configure` vs. `./configure --disable-test` (using `diff`). Unsurprisingly, the only difference is that in this line, `test` is included in the former, and not the latter: 

```
238c238
<       $(call verbose_cmd,echo "userlevel  analysis app aqm ethernet icmp ip simple standard tcpudp test threads" | $(CLICK_BUILDTOOL) findelem -r userlevel -p $(top_srcdir) -X $(srcdir)/elements.exclude $(FINDELEMFLAGS) >,FINDELEMENTS,elements.conf)
---
>       $(call verbose_cmd,echo "userlevel  analysis app aqm ethernet icmp ip simple standard tcpudp threads" | $(CLICK_BUILDTOOL) findelem -r userlevel -p $(top_srcdir) -X $(srcdir)/elements.exclude $(FINDELEMFLAGS) >,FINDELEMENTS,elements.conf)
```  

As an experiment, I modified `Userlevel/Makefile` (generated by `./configure --disable-test`)to add `clp.o` to `OBJS`: `OBJS = $(ELEMENT_OBJS) $(ELEMENTSCONF)$(ELEMENTSSUFFIX).o clp.o click.o`, which is used by the `packetmill` target. I then ran `sudo make clean && sudo make install -j 8` without reconfiguring (since it would overwrite the modified Makefile), and **Bingo ! It builds :**

```
  CXXLINK packetmill.cc
  INSTALL /usr/local/bin/click
  INSTALL /usr/local/bin/packetmill
make[1]: Leaving directory '/home/vboxuser/fastclick-git/fastclick/userlevel'
```

This leads to my hypothesis : `elements/test/clptest.cc` includes `clp.h`, which makes it available to the `packetmill` target in `userlevel/Makefile`. When using `--disable-test`, clp is not included by `clptest.cc`, hence Packetmill fails to build. 

Proposed solution (tested locally, configuring with `--disable-test`, cleaning, and building ; it works) :

replace

https://github.com/tbarbette/fastclick/blob/91a3454b9755e38e84e4872ae6286539e1f45b36/userlevel/Makefile.in#L102

with

`OBJS = $(ELEMENT_OBJS) $(ELEMENTSCONF)$(ELEMENTSSUFFIX).o clp.o click.o`

Do you find the explanation and/or the proposed solution satisfactory ? If so, I'll go ahead and open a PR to fix the issue.

**Comment by tbarbette** [comment]
Yes, please do a PR :)
