### ISSUE TITLE
DPDK: Could not allocate packet MBuf pools : error 12 (Cannot allocate memory)

### ISSUE THREAD

**Issue by kthkaya** [tbarbette/fastclick#53]
Hi,

I am trying to get started with DPDK & fastclick. DPDK 17.05 is installed. I also have openvswitch installed and configured to work with DPDK in the same machine, which works just fine.

Here is my simpletest.click

`FromDPDKDevice(0, PROMISC true) -> CheckIPHeader(OFFSET 14) -> ToDPDKDevice(1);
FromDPDKDevice(1, PROMISC true) -> CheckIPHeader(OFFSET 14) -> ToDPDKDevice(0);
`

Hugepages utilization

root@T-Dev:/home/tdev# cat /proc/meminfo | grep Huge
AnonHugePages:      6144 kB
ShmemHugePages:        0 kB
HugePages_Total:    1024
HugePages_Free:     1024
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB

Running the click code and the error

root@T-Dev:/home/tdev/git/fastclick/thesistest# click --dpdk -c 0xf -n 4 -- simpletest.click
EAL: Detected 4 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:00:03.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
EAL: PCI device 0000:00:09.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
Initializing DPDK
simpletest.click:2: While initializing ‘ToDPDKDevice@6 :: ToDPDKDevice’:
  Could not allocate packet MBuf pools : error 12 (Cannot allocate memory)
Router could not be initialized!

Hugepages utilization after above error 

root@T-Dev:/home/tdev/git/fastclick/thesistest# cat /proc/meminfo | grep Huge
AnonHugePages:      6144 kB
ShmemHugePages:        0 kB
HugePages_Total:    1024
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB

Any ideas?
Thanks

**Comment by gkatsikas** [comment]
Do you get the same error when you run DPDK's testpmd?
Please post the results here.
I am guessing that you allocated very little space for huge pages, hence you might have exactly the same problem with testpmd (not a problem of FastClick).
You might need to enlarge the memory for mbufs using DPDKInfo.

**Comment by kthkaya** [comment]
Hi Georgios, 

Thanks for your input. You were right, testpmd crashed with the same error. Later I did some digging in hugepages setup, removed the following line from grub

GRUB_CMDLINE_LINUX_DEFAULT="default_hugepagesz=512M hugepagesz=512M hugepages=4 hugepagesz=2M hugepages=512

and instead added vm.nr_hugepages=1024 into sysctl.conf.

Now it works, thanks for pointing me in the right direction. However, I couldn't reproduce the problem. I reverted to the initial config and it still works. The only difference I see is that AnonHugePages is 0 this time before I start the click code. 

I will report back if I manage to reproduce it.

**Comment by gkatsikas** [comment]
Hi,

Glad to hear that your problem is solved:

Consider adding this line (or a similar allocation) back to grub if your
system has enough DRAM:
GRUB_CMDLINE_LINUX_DEFAULT=".. default_hugepagesz=1GB hugepagesz=1G
hugepages=32 .. "

The more space you allocate the lower the chance to see this problem again.

**Comment by kthkaya** [comment]
Thanks :)

**Comment by tbarbette** [comment]
Maybe we could suggest a resolution in the error message?

**Comment by gkatsikas** [comment]
Yes, that's easy to do :)
