### ISSUE TITLE
What is the ideal means to connect fastclick app to ovs in a DPDK dataplane?

### ISSUE THREAD

**Issue by kthkaya** [tbarbette/fastclick#54]
Hello,

Prior to DPDK, I was instantiating click apps in linux namespaces and connecting the NSes to ovs switch running on the same machine using virtual ethernet (veth) pairs.  

Now I am investigating whether the same approach is still viable for fast processing via DPDK or not. Some sources such as[this link](http://dpdk.org/ml/archives/users/2017-June/002043.html) made me think a little bit and I wanted to ask your opinions.  

Thanks!

**Comment by tbarbette** [comment]
You can use FromDPDKRing/ToDPDKRing to open a DPDK ring with OVS. You'll have to run Click as a secondary process.
The veth will be awfully slow indeed...

**Comment by gkatsikas** [comment]
OVS-DPDK is still quite slow, especially if you increase the number of hops through these DPDK rings.
If your Click apps are independent, you could alternatively consider using your NIC as a traffic dispatcher and attach each Click app to a dedicated hardware queue.

**Comment by kthkaya** [comment]
This is so helpful, thanks guys.

The click apps are independent; i.e. FW NAT IPS each connected to an individual ovs switch of their own and ovs switches take care of the chaining. At this point I am not planning to test long chains, however I am curious about the HW queue approach. I will read some more and get back with more questions.
