### ISSUE TITLE
Measuring the average cpu cycle rate of a pipeline per second

### ISSUE THREAD

**Issue by kthkaya** [tbarbette/fastclick#69]
Hi,

I am looking for a way to measure the average rate of cpu cycles that a pipeline of batch supporting elements take. Is it doable with the *CycleCount family of elements? If so, can you point me to a testie/sample config?

Thanks

**Comment by tbarbette** [comment]
Never used those... Sorry.

**Comment by kthkaya** [comment]
Thanks for the response Tom. Could you think of another way with the existing elements? If not, does there exist an element that could give a clue about the CPU/resource utilization of a pipeline/or the entire click code?

**Comment by tbarbette** [comment]
Measuring the amount of time/cpu cycles around a push_batch seems right. If you do that just after the FromDPDKDevice you'll have a good information.

**Comment by kthkaya** [comment]
Thanks!
