### ISSUE TITLE
Double free after Packet::expensive_push with enable-netmap-pool

### ISSUE THREAD

**Issue by piotrjurkiewicz** [tbarbette/fastclick#73]
Results in a crash.

Does not occur without `--enable-netmap-pool`.

The simplest way to reproduce is to forward a packet received with `FromNetmapDevice` to `KernelTap` element. `KernelTap` calls `Packet::push(4)`, which turns into `Packet::expensive_push`, since there is no headroom in a Netmap packet. `Packet::expensive_push` calls `Packet::expensive_uniqueify` which frees the packet and allocates a new one. After the push, `KernelTap` writes packet content to TAP and calls `Packet::kill`. Probably this is the moment, when the double free happens.

To reproduce you can use a veth pair, either patched or emulated.

Preparation:

```
insmod /usr/local/lib/netmap.ko
ip link add type veth
ip link set veth0 up
ip link set veth1 up
```

Then run the following configuration:

```
define($burst 32)

kt :: KernelTap(192.168.5.1/24);
kt -> Discard;
FromNetmapDevice("netmap:veth1", BURST $burst) -> Print("Received FromNetmapDevice, forwarded to KernelTap", ACTIVE 1) -> kt;
```

Click process will crash after a while, when kernel will send any packet to veth0:

```
root@localhost:/merged# click famtar/test/kill.click
[  136.367326] 966.520454 [1262] generic_netmap_attach     Emulated adapter for veth1 created (prev was           (null))
966.520336 nm_open [861] overriding ARG3 4096
[  136.455915] 966.609050 [ 441] generic_netmap_register   Emulated adapter for veth1 activated
[  136.457532] 966.610669 [ 486] generic_netmap_register   Emulated adapter: ring 'veth1 RX0' activated
[  136.459186] 966.612324 [ 493] generic_netmap_register   Emulated adapter: ring 'veth1 TX0' activated
[  136.460879] 966.614016 [ 818] tc_configure              ifp veth1 qdisc netmapemu parent 4294967295 handle 0
Allocated 4096 buffers from Netmap buffer pool
966.617968 nm_open [874] overriding ifname veth1 ringid 0x1000 flags 0x4
966.617997 nm_mmap [984] do not mmap, inherit from parent
Received FromNetmapDevice, forwarded to KernelTap:   70 | 33330000 00026631 82953e2d 86dd6000 00000010 3afffe80
expensive Packet::push; have 0 wanted 4
free(): invalid pointer
[  160.758624] 990.912471 [ 818] tc_configure              ifp veth1 qdisc pfifo parent 4294967295 handle 0
[  160.761353] 990.915204 [ 352] generic_netmap_unregister Emulated adapter: ring 'veth1 RX0' deactivated
[  160.763998] 990.917850 [ 359] generic_netmap_unregister Emulated adapter: ring 'veth1 TX0' deactivated
[  160.766231] 990.920084 [ 416] generic_netmap_unregister Emulated adapter for veth1 deactivated
[  160.768852] 990.922704 [1168] generic_netmap_dtor       Emulated netmap adapter for veth1 destroyed
Aborted
```

To induce a crash faster, you can set some IP address on veth0 and ping some random IP address in the same subnet. Kernel will send an ARP request to veth0, which received in Click from veth1 will crash it.

```
ip addr add 192.168.6.1/24 dev veth0
ping 192.168.6.2
```

As I already have mentioned, the same happens with patched veth module. The only difference is that kernel prints:

    [ 8661.060906] 237.928916 [1056] netmap_obj_free           ouch, double free on buffer 53250

at the crash moment.

**Comment by tbarbette** [comment]
Tanks for the detailed issue ! I always used --enable-netmap-pool lately.  And more generally DPDK... 

I'm looking into that right now.

**Comment by tbarbette** [comment]
Fixed.
