### ISSUE TITLE
Efficient static parameters

### ISSUE THREAD

**Issue by tbarbette** [tbarbette/fastclick#94]
It would be great to have some way to fix parameters at compile time. E.g., avoid run-time checks when those parameters are fixed, like

`
Element<STATICPARAM true>(PARAM 5, ...)
`

Btw, I converted the card from https://github.com/tbarbette/fastclick/projects/1 which appear to not be very great for discussions.  Feel free to leave ideas there and convert them to issue when you want to start implementing them and/or want to start a discussion to make the idea more mature. 

The easiest path is to modify the EXPORT_ELEMENT to allow some kind of alias, and then define, eg :

`
template class FromDPDKDevice<bool is_kni>
`

and then :

```
EXPORT_ELEMENT(FromDPDKDevice, FromDPDKDevice<false>)
EXPORT_ELEMENT(FromDPDKKNIDevice, FromDPDKDevice<true>)
```

This to avoid a costly branch in the fast path.

The longer road would be to have some tool like click-devirtualize that actually duplicate the source to compile a version of fromdpdkdevice.cc where all occurences of a normal parameter are replaced by the value of the config file. The advantage for the method is that it allows to replace any parameter to any value. Eg, with the template method if we want to allow int replacement, we need to declare a template for each possible int...

**Comment by tbarbette** [comment]
Maybe @cffs you have input to propose using C++ 14+ language facilities?
Again we could use source-to-source rewriting.

**Comment by cffs** [comment]
If we manage to have a tool to propagate configuration parameters into the element code, and generate a number of element variants for different parameter sets, there is a risk of code size explosion, which might actually be detrimental to overall performance.
Maybe it should be restricted to a few important parameters which really affect the fastpath performance. Those could be chosen by the element developer (*e.g.* using the template approach outlined above), or by the configuration author (by adding a configuration keyword, something like `FromDPDKDevice(STATIC true, ...)`, and then calling some `click-propagate-params` tool).

**Comment by tbarbette** [comment]
Do you thing code size is really a problem? The unused code will not be accessed, it will sit in RAM, yes, but RAM is cheap and as long as it does not pollute the cache we do not really care.
High-speed equipments-wise. We should definitely keep a "small binary" option that deactivates the feature, as some people use Click in embedded devices.

**Comment by cffs** [comment]
I was more thinking about instructions cache problems.
If the different variants are served by different cores (*e.g.* multiple `FromDPDKDevice` on different threads), this is not an issue, and *specializing* would likely be better.
However, you might also have many variants of an element on the same path and served by the same core. In this case, it may happen that instructions from one variant need to be trashed from cache to make room for instructions of another variant (depending on cache size and amount of code on the path). That can be costly if done for every batch of packets. In this case, a single element with one additional branch might give better performance if it can avoid caching issues.

**Comment by tbarbette** [comment]
Ok we agree then. Let's allow specific designated parameters, and somehow warn the user to keep in mind not to use specialized versions too much. The template idea force the specialization though...

**Comment by tbarbette** [comment]
Well I'm happy to say this feature will be (partially) the subject of our upcoming ASPLOS'21 paper "PacketMill". Therefore closing it :) See https://github.com/aliireza/packetmill

**Comment by aquatoney** [comment]
a Big Congrats!
